package com.cloud.platform.mapper;

import com.cloud.platform.model.AccessoryType;
import com.cloud.platform.model.AccessoryTypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface AccessoryTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accessory_type
     *
     * @mbg.generated Sat Apr 25 17:58:35 CST 2020
     */
    long countByExample(AccessoryTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accessory_type
     *
     * @mbg.generated Sat Apr 25 17:58:35 CST 2020
     */
    int deleteByExample(AccessoryTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accessory_type
     *
     * @mbg.generated Sat Apr 25 17:58:35 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accessory_type
     *
     * @mbg.generated Sat Apr 25 17:58:35 CST 2020
     */
    int insert(AccessoryType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accessory_type
     *
     * @mbg.generated Sat Apr 25 17:58:35 CST 2020
     */
    int insertSelective(AccessoryType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accessory_type
     *
     * @mbg.generated Sat Apr 25 17:58:35 CST 2020
     */
    List<AccessoryType> selectByExampleWithRowbounds(AccessoryTypeExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accessory_type
     *
     * @mbg.generated Sat Apr 25 17:58:35 CST 2020
     */
    List<AccessoryType> selectByExample(AccessoryTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accessory_type
     *
     * @mbg.generated Sat Apr 25 17:58:35 CST 2020
     */
    AccessoryType selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accessory_type
     *
     * @mbg.generated Sat Apr 25 17:58:35 CST 2020
     */
    int updateByExampleSelective(@Param("record") AccessoryType record, @Param("example") AccessoryTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accessory_type
     *
     * @mbg.generated Sat Apr 25 17:58:35 CST 2020
     */
    int updateByExample(@Param("record") AccessoryType record, @Param("example") AccessoryTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accessory_type
     *
     * @mbg.generated Sat Apr 25 17:58:35 CST 2020
     */
    int updateByPrimaryKeySelective(AccessoryType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accessory_type
     *
     * @mbg.generated Sat Apr 25 17:58:35 CST 2020
     */
    int updateByPrimaryKey(AccessoryType record);
}