package com.cloud.platform.mapper;

import com.cloud.platform.model.DetectOrder;
import com.cloud.platform.model.DetectOrderExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface DetectOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detect_order
     *
     * @mbg.generated Sun Apr 26 13:17:26 CST 2020
     */
    long countByExample(DetectOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detect_order
     *
     * @mbg.generated Sun Apr 26 13:17:26 CST 2020
     */
    int deleteByExample(DetectOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detect_order
     *
     * @mbg.generated Sun Apr 26 13:17:26 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detect_order
     *
     * @mbg.generated Sun Apr 26 13:17:26 CST 2020
     */
    int insert(DetectOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detect_order
     *
     * @mbg.generated Sun Apr 26 13:17:26 CST 2020
     */
    int insertSelective(DetectOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detect_order
     *
     * @mbg.generated Sun Apr 26 13:17:26 CST 2020
     */
    List<DetectOrder> selectByExampleWithRowbounds(DetectOrderExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detect_order
     *
     * @mbg.generated Sun Apr 26 13:17:26 CST 2020
     */
    List<DetectOrder> selectByExample(DetectOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detect_order
     *
     * @mbg.generated Sun Apr 26 13:17:26 CST 2020
     */
    DetectOrder selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detect_order
     *
     * @mbg.generated Sun Apr 26 13:17:26 CST 2020
     */
    int updateByExampleSelective(@Param("record") DetectOrder record, @Param("example") DetectOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detect_order
     *
     * @mbg.generated Sun Apr 26 13:17:26 CST 2020
     */
    int updateByExample(@Param("record") DetectOrder record, @Param("example") DetectOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detect_order
     *
     * @mbg.generated Sun Apr 26 13:17:26 CST 2020
     */
    int updateByPrimaryKeySelective(DetectOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detect_order
     *
     * @mbg.generated Sun Apr 26 13:17:26 CST 2020
     */
    int updateByPrimaryKey(DetectOrder record);
}