package com.cloud.platform.mapper;

import com.cloud.platform.model.DeviceErrorCode;
import com.cloud.platform.model.DeviceErrorCodeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface DeviceErrorCodeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_error_code
     *
     * @mbg.generated Mon Apr 27 21:47:54 CST 2020
     */
    long countByExample(DeviceErrorCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_error_code
     *
     * @mbg.generated Mon Apr 27 21:47:54 CST 2020
     */
    int deleteByExample(DeviceErrorCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_error_code
     *
     * @mbg.generated Mon Apr 27 21:47:54 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_error_code
     *
     * @mbg.generated Mon Apr 27 21:47:54 CST 2020
     */
    int insert(DeviceErrorCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_error_code
     *
     * @mbg.generated Mon Apr 27 21:47:54 CST 2020
     */
    int insertSelective(DeviceErrorCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_error_code
     *
     * @mbg.generated Mon Apr 27 21:47:54 CST 2020
     */
    List<DeviceErrorCode> selectByExampleWithRowbounds(DeviceErrorCodeExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_error_code
     *
     * @mbg.generated Mon Apr 27 21:47:54 CST 2020
     */
    List<DeviceErrorCode> selectByExample(DeviceErrorCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_error_code
     *
     * @mbg.generated Mon Apr 27 21:47:54 CST 2020
     */
    DeviceErrorCode selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_error_code
     *
     * @mbg.generated Mon Apr 27 21:47:54 CST 2020
     */
    int updateByExampleSelective(@Param("record") DeviceErrorCode record, @Param("example") DeviceErrorCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_error_code
     *
     * @mbg.generated Mon Apr 27 21:47:54 CST 2020
     */
    int updateByExample(@Param("record") DeviceErrorCode record, @Param("example") DeviceErrorCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_error_code
     *
     * @mbg.generated Mon Apr 27 21:47:54 CST 2020
     */
    int updateByPrimaryKeySelective(DeviceErrorCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_error_code
     *
     * @mbg.generated Mon Apr 27 21:47:54 CST 2020
     */
    int updateByPrimaryKey(DeviceErrorCode record);
}