package com.cloud.platform.mapper;

import com.cloud.platform.model.ServerInfo;
import com.cloud.platform.model.ServerInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface ServerInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table servers_info
     *
     * @mbg.generated Sat Apr 25 17:58:34 CST 2020
     */
    long countByExample(ServerInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table servers_info
     *
     * @mbg.generated Sat Apr 25 17:58:34 CST 2020
     */
    int deleteByExample(ServerInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table servers_info
     *
     * @mbg.generated Sat Apr 25 17:58:34 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table servers_info
     *
     * @mbg.generated Sat Apr 25 17:58:34 CST 2020
     */
    int insert(ServerInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table servers_info
     *
     * @mbg.generated Sat Apr 25 17:58:34 CST 2020
     */
    int insertSelective(ServerInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table servers_info
     *
     * @mbg.generated Sat Apr 25 17:58:34 CST 2020
     */
    List<ServerInfo> selectByExampleWithRowbounds(ServerInfoExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table servers_info
     *
     * @mbg.generated Sat Apr 25 17:58:34 CST 2020
     */
    List<ServerInfo> selectByExample(ServerInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table servers_info
     *
     * @mbg.generated Sat Apr 25 17:58:34 CST 2020
     */
    ServerInfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table servers_info
     *
     * @mbg.generated Sat Apr 25 17:58:34 CST 2020
     */
    int updateByExampleSelective(@Param("record") ServerInfo record, @Param("example") ServerInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table servers_info
     *
     * @mbg.generated Sat Apr 25 17:58:34 CST 2020
     */
    int updateByExample(@Param("record") ServerInfo record, @Param("example") ServerInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table servers_info
     *
     * @mbg.generated Sat Apr 25 17:58:34 CST 2020
     */
    int updateByPrimaryKeySelective(ServerInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table servers_info
     *
     * @mbg.generated Sat Apr 25 17:58:34 CST 2020
     */
    int updateByPrimaryKey(ServerInfo record);
}