package com.cloud.platform.mapper;

import com.cloud.platform.model.UnAssetDevice;
import com.cloud.platform.model.UnAssetDeviceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface UnAssetDeviceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table un_asset_device
     *
     * @mbg.generated Mon Apr 27 21:47:54 CST 2020
     */
    long countByExample(UnAssetDeviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table un_asset_device
     *
     * @mbg.generated Mon Apr 27 21:47:54 CST 2020
     */
    int deleteByExample(UnAssetDeviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table un_asset_device
     *
     * @mbg.generated Mon Apr 27 21:47:54 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table un_asset_device
     *
     * @mbg.generated Mon Apr 27 21:47:54 CST 2020
     */
    int insert(UnAssetDevice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table un_asset_device
     *
     * @mbg.generated Mon Apr 27 21:47:54 CST 2020
     */
    int insertSelective(UnAssetDevice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table un_asset_device
     *
     * @mbg.generated Mon Apr 27 21:47:54 CST 2020
     */
    List<UnAssetDevice> selectByExampleWithRowbounds(UnAssetDeviceExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table un_asset_device
     *
     * @mbg.generated Mon Apr 27 21:47:54 CST 2020
     */
    List<UnAssetDevice> selectByExample(UnAssetDeviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table un_asset_device
     *
     * @mbg.generated Mon Apr 27 21:47:54 CST 2020
     */
    UnAssetDevice selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table un_asset_device
     *
     * @mbg.generated Mon Apr 27 21:47:54 CST 2020
     */
    int updateByExampleSelective(@Param("record") UnAssetDevice record, @Param("example") UnAssetDeviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table un_asset_device
     *
     * @mbg.generated Mon Apr 27 21:47:54 CST 2020
     */
    int updateByExample(@Param("record") UnAssetDevice record, @Param("example") UnAssetDeviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table un_asset_device
     *
     * @mbg.generated Mon Apr 27 21:47:54 CST 2020
     */
    int updateByPrimaryKeySelective(UnAssetDevice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table un_asset_device
     *
     * @mbg.generated Mon Apr 27 21:47:54 CST 2020
     */
    int updateByPrimaryKey(UnAssetDevice record);
}