package com.cloud.platform.model;

import java.util.ArrayList;
import java.util.List;

public class AccessoryDeviceExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table accessory_device
     *
     * @mbg.generated Sun Apr 26 13:17:26 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table accessory_device
     *
     * @mbg.generated Sun Apr 26 13:17:26 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table accessory_device
     *
     * @mbg.generated Sun Apr 26 13:17:26 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accessory_device
     *
     * @mbg.generated Sun Apr 26 13:17:26 CST 2020
     */
    public AccessoryDeviceExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accessory_device
     *
     * @mbg.generated Sun Apr 26 13:17:26 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accessory_device
     *
     * @mbg.generated Sun Apr 26 13:17:26 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accessory_device
     *
     * @mbg.generated Sun Apr 26 13:17:26 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accessory_device
     *
     * @mbg.generated Sun Apr 26 13:17:26 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accessory_device
     *
     * @mbg.generated Sun Apr 26 13:17:26 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accessory_device
     *
     * @mbg.generated Sun Apr 26 13:17:26 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accessory_device
     *
     * @mbg.generated Sun Apr 26 13:17:26 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accessory_device
     *
     * @mbg.generated Sun Apr 26 13:17:26 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accessory_device
     *
     * @mbg.generated Sun Apr 26 13:17:26 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accessory_device
     *
     * @mbg.generated Sun Apr 26 13:17:26 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table accessory_device
     *
     * @mbg.generated Sun Apr 26 13:17:26 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andAffiliationIsNull() {
            addCriterion("affiliation is null");
            return (Criteria) this;
        }

        public Criteria andAffiliationIsNotNull() {
            addCriterion("affiliation is not null");
            return (Criteria) this;
        }

        public Criteria andAffiliationEqualTo(String value) {
            addCriterion("affiliation =", value, "affiliation");
            return (Criteria) this;
        }

        public Criteria andAffiliationNotEqualTo(String value) {
            addCriterion("affiliation <>", value, "affiliation");
            return (Criteria) this;
        }

        public Criteria andAffiliationGreaterThan(String value) {
            addCriterion("affiliation >", value, "affiliation");
            return (Criteria) this;
        }

        public Criteria andAffiliationGreaterThanOrEqualTo(String value) {
            addCriterion("affiliation >=", value, "affiliation");
            return (Criteria) this;
        }

        public Criteria andAffiliationLessThan(String value) {
            addCriterion("affiliation <", value, "affiliation");
            return (Criteria) this;
        }

        public Criteria andAffiliationLessThanOrEqualTo(String value) {
            addCriterion("affiliation <=", value, "affiliation");
            return (Criteria) this;
        }

        public Criteria andAffiliationLike(String value) {
            addCriterion("affiliation like", value, "affiliation");
            return (Criteria) this;
        }

        public Criteria andAffiliationNotLike(String value) {
            addCriterion("affiliation not like", value, "affiliation");
            return (Criteria) this;
        }

        public Criteria andAffiliationIn(List<String> values) {
            addCriterion("affiliation in", values, "affiliation");
            return (Criteria) this;
        }

        public Criteria andAffiliationNotIn(List<String> values) {
            addCriterion("affiliation not in", values, "affiliation");
            return (Criteria) this;
        }

        public Criteria andAffiliationBetween(String value1, String value2) {
            addCriterion("affiliation between", value1, value2, "affiliation");
            return (Criteria) this;
        }

        public Criteria andAffiliationNotBetween(String value1, String value2) {
            addCriterion("affiliation not between", value1, value2, "affiliation");
            return (Criteria) this;
        }

        public Criteria andAffiliateDeviceIsNull() {
            addCriterion("affiliate_device is null");
            return (Criteria) this;
        }

        public Criteria andAffiliateDeviceIsNotNull() {
            addCriterion("affiliate_device is not null");
            return (Criteria) this;
        }

        public Criteria andAffiliateDeviceEqualTo(String value) {
            addCriterion("affiliate_device =", value, "affiliateDevice");
            return (Criteria) this;
        }

        public Criteria andAffiliateDeviceNotEqualTo(String value) {
            addCriterion("affiliate_device <>", value, "affiliateDevice");
            return (Criteria) this;
        }

        public Criteria andAffiliateDeviceGreaterThan(String value) {
            addCriterion("affiliate_device >", value, "affiliateDevice");
            return (Criteria) this;
        }

        public Criteria andAffiliateDeviceGreaterThanOrEqualTo(String value) {
            addCriterion("affiliate_device >=", value, "affiliateDevice");
            return (Criteria) this;
        }

        public Criteria andAffiliateDeviceLessThan(String value) {
            addCriterion("affiliate_device <", value, "affiliateDevice");
            return (Criteria) this;
        }

        public Criteria andAffiliateDeviceLessThanOrEqualTo(String value) {
            addCriterion("affiliate_device <=", value, "affiliateDevice");
            return (Criteria) this;
        }

        public Criteria andAffiliateDeviceLike(String value) {
            addCriterion("affiliate_device like", value, "affiliateDevice");
            return (Criteria) this;
        }

        public Criteria andAffiliateDeviceNotLike(String value) {
            addCriterion("affiliate_device not like", value, "affiliateDevice");
            return (Criteria) this;
        }

        public Criteria andAffiliateDeviceIn(List<String> values) {
            addCriterion("affiliate_device in", values, "affiliateDevice");
            return (Criteria) this;
        }

        public Criteria andAffiliateDeviceNotIn(List<String> values) {
            addCriterion("affiliate_device not in", values, "affiliateDevice");
            return (Criteria) this;
        }

        public Criteria andAffiliateDeviceBetween(String value1, String value2) {
            addCriterion("affiliate_device between", value1, value2, "affiliateDevice");
            return (Criteria) this;
        }

        public Criteria andAffiliateDeviceNotBetween(String value1, String value2) {
            addCriterion("affiliate_device not between", value1, value2, "affiliateDevice");
            return (Criteria) this;
        }

        public Criteria andAccessoryNameIsNull() {
            addCriterion("accessory_name is null");
            return (Criteria) this;
        }

        public Criteria andAccessoryNameIsNotNull() {
            addCriterion("accessory_name is not null");
            return (Criteria) this;
        }

        public Criteria andAccessoryNameEqualTo(String value) {
            addCriterion("accessory_name =", value, "accessoryName");
            return (Criteria) this;
        }

        public Criteria andAccessoryNameNotEqualTo(String value) {
            addCriterion("accessory_name <>", value, "accessoryName");
            return (Criteria) this;
        }

        public Criteria andAccessoryNameGreaterThan(String value) {
            addCriterion("accessory_name >", value, "accessoryName");
            return (Criteria) this;
        }

        public Criteria andAccessoryNameGreaterThanOrEqualTo(String value) {
            addCriterion("accessory_name >=", value, "accessoryName");
            return (Criteria) this;
        }

        public Criteria andAccessoryNameLessThan(String value) {
            addCriterion("accessory_name <", value, "accessoryName");
            return (Criteria) this;
        }

        public Criteria andAccessoryNameLessThanOrEqualTo(String value) {
            addCriterion("accessory_name <=", value, "accessoryName");
            return (Criteria) this;
        }

        public Criteria andAccessoryNameLike(String value) {
            addCriterion("accessory_name like", value, "accessoryName");
            return (Criteria) this;
        }

        public Criteria andAccessoryNameNotLike(String value) {
            addCriterion("accessory_name not like", value, "accessoryName");
            return (Criteria) this;
        }

        public Criteria andAccessoryNameIn(List<String> values) {
            addCriterion("accessory_name in", values, "accessoryName");
            return (Criteria) this;
        }

        public Criteria andAccessoryNameNotIn(List<String> values) {
            addCriterion("accessory_name not in", values, "accessoryName");
            return (Criteria) this;
        }

        public Criteria andAccessoryNameBetween(String value1, String value2) {
            addCriterion("accessory_name between", value1, value2, "accessoryName");
            return (Criteria) this;
        }

        public Criteria andAccessoryNameNotBetween(String value1, String value2) {
            addCriterion("accessory_name not between", value1, value2, "accessoryName");
            return (Criteria) this;
        }

        public Criteria andAccessoryTypeIsNull() {
            addCriterion("accessory_type is null");
            return (Criteria) this;
        }

        public Criteria andAccessoryTypeIsNotNull() {
            addCriterion("accessory_type is not null");
            return (Criteria) this;
        }

        public Criteria andAccessoryTypeEqualTo(String value) {
            addCriterion("accessory_type =", value, "accessoryType");
            return (Criteria) this;
        }

        public Criteria andAccessoryTypeNotEqualTo(String value) {
            addCriterion("accessory_type <>", value, "accessoryType");
            return (Criteria) this;
        }

        public Criteria andAccessoryTypeGreaterThan(String value) {
            addCriterion("accessory_type >", value, "accessoryType");
            return (Criteria) this;
        }

        public Criteria andAccessoryTypeGreaterThanOrEqualTo(String value) {
            addCriterion("accessory_type >=", value, "accessoryType");
            return (Criteria) this;
        }

        public Criteria andAccessoryTypeLessThan(String value) {
            addCriterion("accessory_type <", value, "accessoryType");
            return (Criteria) this;
        }

        public Criteria andAccessoryTypeLessThanOrEqualTo(String value) {
            addCriterion("accessory_type <=", value, "accessoryType");
            return (Criteria) this;
        }

        public Criteria andAccessoryTypeLike(String value) {
            addCriterion("accessory_type like", value, "accessoryType");
            return (Criteria) this;
        }

        public Criteria andAccessoryTypeNotLike(String value) {
            addCriterion("accessory_type not like", value, "accessoryType");
            return (Criteria) this;
        }

        public Criteria andAccessoryTypeIn(List<String> values) {
            addCriterion("accessory_type in", values, "accessoryType");
            return (Criteria) this;
        }

        public Criteria andAccessoryTypeNotIn(List<String> values) {
            addCriterion("accessory_type not in", values, "accessoryType");
            return (Criteria) this;
        }

        public Criteria andAccessoryTypeBetween(String value1, String value2) {
            addCriterion("accessory_type between", value1, value2, "accessoryType");
            return (Criteria) this;
        }

        public Criteria andAccessoryTypeNotBetween(String value1, String value2) {
            addCriterion("accessory_type not between", value1, value2, "accessoryType");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table accessory_device
     *
     * @mbg.generated do_not_delete_during_merge Sun Apr 26 13:17:26 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table accessory_device
     *
     * @mbg.generated Sun Apr 26 13:17:26 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}