package com.cloud.platform.model;

public class AccessoryDevice {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accessory_device.id
     *
     * @mbg.generated Mon Apr 27 21:47:54 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accessory_device.affiliation
     *
     * @mbg.generated Mon Apr 27 21:47:54 CST 2020
     */
    private String affiliation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accessory_device.affiliate_device
     *
     * @mbg.generated Mon Apr 27 21:47:54 CST 2020
     */
    private String affiliateDevice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accessory_device.accessory_name
     *
     * @mbg.generated Mon Apr 27 21:47:54 CST 2020
     */
    private String accessoryName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accessory_device.accessory_type
     *
     * @mbg.generated Mon Apr 27 21:47:54 CST 2020
     */
    private String accessoryType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accessory_device.id
     *
     * @return the value of accessory_device.id
     *
     * @mbg.generated Mon Apr 27 21:47:54 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accessory_device.id
     *
     * @param id the value for accessory_device.id
     *
     * @mbg.generated Mon Apr 27 21:47:54 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accessory_device.affiliation
     *
     * @return the value of accessory_device.affiliation
     *
     * @mbg.generated Mon Apr 27 21:47:54 CST 2020
     */
    public String getAffiliation() {
        return affiliation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accessory_device.affiliation
     *
     * @param affiliation the value for accessory_device.affiliation
     *
     * @mbg.generated Mon Apr 27 21:47:54 CST 2020
     */
    public void setAffiliation(String affiliation) {
        this.affiliation = affiliation == null ? null : affiliation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accessory_device.affiliate_device
     *
     * @return the value of accessory_device.affiliate_device
     *
     * @mbg.generated Mon Apr 27 21:47:54 CST 2020
     */
    public String getAffiliateDevice() {
        return affiliateDevice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accessory_device.affiliate_device
     *
     * @param affiliateDevice the value for accessory_device.affiliate_device
     *
     * @mbg.generated Mon Apr 27 21:47:54 CST 2020
     */
    public void setAffiliateDevice(String affiliateDevice) {
        this.affiliateDevice = affiliateDevice == null ? null : affiliateDevice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accessory_device.accessory_name
     *
     * @return the value of accessory_device.accessory_name
     *
     * @mbg.generated Mon Apr 27 21:47:54 CST 2020
     */
    public String getAccessoryName() {
        return accessoryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accessory_device.accessory_name
     *
     * @param accessoryName the value for accessory_device.accessory_name
     *
     * @mbg.generated Mon Apr 27 21:47:54 CST 2020
     */
    public void setAccessoryName(String accessoryName) {
        this.accessoryName = accessoryName == null ? null : accessoryName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accessory_device.accessory_type
     *
     * @return the value of accessory_device.accessory_type
     *
     * @mbg.generated Mon Apr 27 21:47:54 CST 2020
     */
    public String getAccessoryType() {
        return accessoryType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accessory_device.accessory_type
     *
     * @param accessoryType the value for accessory_device.accessory_type
     *
     * @mbg.generated Mon Apr 27 21:47:54 CST 2020
     */
    public void setAccessoryType(String accessoryType) {
        this.accessoryType = accessoryType == null ? null : accessoryType.trim();
    }
}