package com.cloud.platform.model;

import java.util.ArrayList;
import java.util.List;

public class DetectOrderExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table detect_order
     *
     * @mbg.generated Sun Apr 26 13:17:26 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table detect_order
     *
     * @mbg.generated Sun Apr 26 13:17:26 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table detect_order
     *
     * @mbg.generated Sun Apr 26 13:17:26 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detect_order
     *
     * @mbg.generated Sun Apr 26 13:17:26 CST 2020
     */
    public DetectOrderExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detect_order
     *
     * @mbg.generated Sun Apr 26 13:17:26 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detect_order
     *
     * @mbg.generated Sun Apr 26 13:17:26 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detect_order
     *
     * @mbg.generated Sun Apr 26 13:17:26 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detect_order
     *
     * @mbg.generated Sun Apr 26 13:17:26 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detect_order
     *
     * @mbg.generated Sun Apr 26 13:17:26 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detect_order
     *
     * @mbg.generated Sun Apr 26 13:17:26 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detect_order
     *
     * @mbg.generated Sun Apr 26 13:17:26 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detect_order
     *
     * @mbg.generated Sun Apr 26 13:17:26 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detect_order
     *
     * @mbg.generated Sun Apr 26 13:17:26 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detect_order
     *
     * @mbg.generated Sun Apr 26 13:17:26 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table detect_order
     *
     * @mbg.generated Sun Apr 26 13:17:26 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andAffiliationIsNull() {
            addCriterion("affiliation is null");
            return (Criteria) this;
        }

        public Criteria andAffiliationIsNotNull() {
            addCriterion("affiliation is not null");
            return (Criteria) this;
        }

        public Criteria andAffiliationEqualTo(String value) {
            addCriterion("affiliation =", value, "affiliation");
            return (Criteria) this;
        }

        public Criteria andAffiliationNotEqualTo(String value) {
            addCriterion("affiliation <>", value, "affiliation");
            return (Criteria) this;
        }

        public Criteria andAffiliationGreaterThan(String value) {
            addCriterion("affiliation >", value, "affiliation");
            return (Criteria) this;
        }

        public Criteria andAffiliationGreaterThanOrEqualTo(String value) {
            addCriterion("affiliation >=", value, "affiliation");
            return (Criteria) this;
        }

        public Criteria andAffiliationLessThan(String value) {
            addCriterion("affiliation <", value, "affiliation");
            return (Criteria) this;
        }

        public Criteria andAffiliationLessThanOrEqualTo(String value) {
            addCriterion("affiliation <=", value, "affiliation");
            return (Criteria) this;
        }

        public Criteria andAffiliationLike(String value) {
            addCriterion("affiliation like", value, "affiliation");
            return (Criteria) this;
        }

        public Criteria andAffiliationNotLike(String value) {
            addCriterion("affiliation not like", value, "affiliation");
            return (Criteria) this;
        }

        public Criteria andAffiliationIn(List<String> values) {
            addCriterion("affiliation in", values, "affiliation");
            return (Criteria) this;
        }

        public Criteria andAffiliationNotIn(List<String> values) {
            addCriterion("affiliation not in", values, "affiliation");
            return (Criteria) this;
        }

        public Criteria andAffiliationBetween(String value1, String value2) {
            addCriterion("affiliation between", value1, value2, "affiliation");
            return (Criteria) this;
        }

        public Criteria andAffiliationNotBetween(String value1, String value2) {
            addCriterion("affiliation not between", value1, value2, "affiliation");
            return (Criteria) this;
        }

        public Criteria andOrderIndexIsNull() {
            addCriterion("order_index is null");
            return (Criteria) this;
        }

        public Criteria andOrderIndexIsNotNull() {
            addCriterion("order_index is not null");
            return (Criteria) this;
        }

        public Criteria andOrderIndexEqualTo(String value) {
            addCriterion("order_index =", value, "orderIndex");
            return (Criteria) this;
        }

        public Criteria andOrderIndexNotEqualTo(String value) {
            addCriterion("order_index <>", value, "orderIndex");
            return (Criteria) this;
        }

        public Criteria andOrderIndexGreaterThan(String value) {
            addCriterion("order_index >", value, "orderIndex");
            return (Criteria) this;
        }

        public Criteria andOrderIndexGreaterThanOrEqualTo(String value) {
            addCriterion("order_index >=", value, "orderIndex");
            return (Criteria) this;
        }

        public Criteria andOrderIndexLessThan(String value) {
            addCriterion("order_index <", value, "orderIndex");
            return (Criteria) this;
        }

        public Criteria andOrderIndexLessThanOrEqualTo(String value) {
            addCriterion("order_index <=", value, "orderIndex");
            return (Criteria) this;
        }

        public Criteria andOrderIndexLike(String value) {
            addCriterion("order_index like", value, "orderIndex");
            return (Criteria) this;
        }

        public Criteria andOrderIndexNotLike(String value) {
            addCriterion("order_index not like", value, "orderIndex");
            return (Criteria) this;
        }

        public Criteria andOrderIndexIn(List<String> values) {
            addCriterion("order_index in", values, "orderIndex");
            return (Criteria) this;
        }

        public Criteria andOrderIndexNotIn(List<String> values) {
            addCriterion("order_index not in", values, "orderIndex");
            return (Criteria) this;
        }

        public Criteria andOrderIndexBetween(String value1, String value2) {
            addCriterion("order_index between", value1, value2, "orderIndex");
            return (Criteria) this;
        }

        public Criteria andOrderIndexNotBetween(String value1, String value2) {
            addCriterion("order_index not between", value1, value2, "orderIndex");
            return (Criteria) this;
        }

        public Criteria andDetectDateIsNull() {
            addCriterion("detect_date is null");
            return (Criteria) this;
        }

        public Criteria andDetectDateIsNotNull() {
            addCriterion("detect_date is not null");
            return (Criteria) this;
        }

        public Criteria andDetectDateEqualTo(String value) {
            addCriterion("detect_date =", value, "detectDate");
            return (Criteria) this;
        }

        public Criteria andDetectDateNotEqualTo(String value) {
            addCriterion("detect_date <>", value, "detectDate");
            return (Criteria) this;
        }

        public Criteria andDetectDateGreaterThan(String value) {
            addCriterion("detect_date >", value, "detectDate");
            return (Criteria) this;
        }

        public Criteria andDetectDateGreaterThanOrEqualTo(String value) {
            addCriterion("detect_date >=", value, "detectDate");
            return (Criteria) this;
        }

        public Criteria andDetectDateLessThan(String value) {
            addCriterion("detect_date <", value, "detectDate");
            return (Criteria) this;
        }

        public Criteria andDetectDateLessThanOrEqualTo(String value) {
            addCriterion("detect_date <=", value, "detectDate");
            return (Criteria) this;
        }

        public Criteria andDetectDateLike(String value) {
            addCriterion("detect_date like", value, "detectDate");
            return (Criteria) this;
        }

        public Criteria andDetectDateNotLike(String value) {
            addCriterion("detect_date not like", value, "detectDate");
            return (Criteria) this;
        }

        public Criteria andDetectDateIn(List<String> values) {
            addCriterion("detect_date in", values, "detectDate");
            return (Criteria) this;
        }

        public Criteria andDetectDateNotIn(List<String> values) {
            addCriterion("detect_date not in", values, "detectDate");
            return (Criteria) this;
        }

        public Criteria andDetectDateBetween(String value1, String value2) {
            addCriterion("detect_date between", value1, value2, "detectDate");
            return (Criteria) this;
        }

        public Criteria andDetectDateNotBetween(String value1, String value2) {
            addCriterion("detect_date not between", value1, value2, "detectDate");
            return (Criteria) this;
        }

        public Criteria andServerIsNull() {
            addCriterion("server is null");
            return (Criteria) this;
        }

        public Criteria andServerIsNotNull() {
            addCriterion("server is not null");
            return (Criteria) this;
        }

        public Criteria andServerEqualTo(String value) {
            addCriterion("server =", value, "server");
            return (Criteria) this;
        }

        public Criteria andServerNotEqualTo(String value) {
            addCriterion("server <>", value, "server");
            return (Criteria) this;
        }

        public Criteria andServerGreaterThan(String value) {
            addCriterion("server >", value, "server");
            return (Criteria) this;
        }

        public Criteria andServerGreaterThanOrEqualTo(String value) {
            addCriterion("server >=", value, "server");
            return (Criteria) this;
        }

        public Criteria andServerLessThan(String value) {
            addCriterion("server <", value, "server");
            return (Criteria) this;
        }

        public Criteria andServerLessThanOrEqualTo(String value) {
            addCriterion("server <=", value, "server");
            return (Criteria) this;
        }

        public Criteria andServerLike(String value) {
            addCriterion("server like", value, "server");
            return (Criteria) this;
        }

        public Criteria andServerNotLike(String value) {
            addCriterion("server not like", value, "server");
            return (Criteria) this;
        }

        public Criteria andServerIn(List<String> values) {
            addCriterion("server in", values, "server");
            return (Criteria) this;
        }

        public Criteria andServerNotIn(List<String> values) {
            addCriterion("server not in", values, "server");
            return (Criteria) this;
        }

        public Criteria andServerBetween(String value1, String value2) {
            addCriterion("server between", value1, value2, "server");
            return (Criteria) this;
        }

        public Criteria andServerNotBetween(String value1, String value2) {
            addCriterion("server not between", value1, value2, "server");
            return (Criteria) this;
        }

        public Criteria andDetectMemberIsNull() {
            addCriterion("detect_member is null");
            return (Criteria) this;
        }

        public Criteria andDetectMemberIsNotNull() {
            addCriterion("detect_member is not null");
            return (Criteria) this;
        }

        public Criteria andDetectMemberEqualTo(String value) {
            addCriterion("detect_member =", value, "detectMember");
            return (Criteria) this;
        }

        public Criteria andDetectMemberNotEqualTo(String value) {
            addCriterion("detect_member <>", value, "detectMember");
            return (Criteria) this;
        }

        public Criteria andDetectMemberGreaterThan(String value) {
            addCriterion("detect_member >", value, "detectMember");
            return (Criteria) this;
        }

        public Criteria andDetectMemberGreaterThanOrEqualTo(String value) {
            addCriterion("detect_member >=", value, "detectMember");
            return (Criteria) this;
        }

        public Criteria andDetectMemberLessThan(String value) {
            addCriterion("detect_member <", value, "detectMember");
            return (Criteria) this;
        }

        public Criteria andDetectMemberLessThanOrEqualTo(String value) {
            addCriterion("detect_member <=", value, "detectMember");
            return (Criteria) this;
        }

        public Criteria andDetectMemberLike(String value) {
            addCriterion("detect_member like", value, "detectMember");
            return (Criteria) this;
        }

        public Criteria andDetectMemberNotLike(String value) {
            addCriterion("detect_member not like", value, "detectMember");
            return (Criteria) this;
        }

        public Criteria andDetectMemberIn(List<String> values) {
            addCriterion("detect_member in", values, "detectMember");
            return (Criteria) this;
        }

        public Criteria andDetectMemberNotIn(List<String> values) {
            addCriterion("detect_member not in", values, "detectMember");
            return (Criteria) this;
        }

        public Criteria andDetectMemberBetween(String value1, String value2) {
            addCriterion("detect_member between", value1, value2, "detectMember");
            return (Criteria) this;
        }

        public Criteria andDetectMemberNotBetween(String value1, String value2) {
            addCriterion("detect_member not between", value1, value2, "detectMember");
            return (Criteria) this;
        }

        public Criteria andRelateOrderIsNull() {
            addCriterion("relate_order is null");
            return (Criteria) this;
        }

        public Criteria andRelateOrderIsNotNull() {
            addCriterion("relate_order is not null");
            return (Criteria) this;
        }

        public Criteria andRelateOrderEqualTo(String value) {
            addCriterion("relate_order =", value, "relateOrder");
            return (Criteria) this;
        }

        public Criteria andRelateOrderNotEqualTo(String value) {
            addCriterion("relate_order <>", value, "relateOrder");
            return (Criteria) this;
        }

        public Criteria andRelateOrderGreaterThan(String value) {
            addCriterion("relate_order >", value, "relateOrder");
            return (Criteria) this;
        }

        public Criteria andRelateOrderGreaterThanOrEqualTo(String value) {
            addCriterion("relate_order >=", value, "relateOrder");
            return (Criteria) this;
        }

        public Criteria andRelateOrderLessThan(String value) {
            addCriterion("relate_order <", value, "relateOrder");
            return (Criteria) this;
        }

        public Criteria andRelateOrderLessThanOrEqualTo(String value) {
            addCriterion("relate_order <=", value, "relateOrder");
            return (Criteria) this;
        }

        public Criteria andRelateOrderLike(String value) {
            addCriterion("relate_order like", value, "relateOrder");
            return (Criteria) this;
        }

        public Criteria andRelateOrderNotLike(String value) {
            addCriterion("relate_order not like", value, "relateOrder");
            return (Criteria) this;
        }

        public Criteria andRelateOrderIn(List<String> values) {
            addCriterion("relate_order in", values, "relateOrder");
            return (Criteria) this;
        }

        public Criteria andRelateOrderNotIn(List<String> values) {
            addCriterion("relate_order not in", values, "relateOrder");
            return (Criteria) this;
        }

        public Criteria andRelateOrderBetween(String value1, String value2) {
            addCriterion("relate_order between", value1, value2, "relateOrder");
            return (Criteria) this;
        }

        public Criteria andRelateOrderNotBetween(String value1, String value2) {
            addCriterion("relate_order not between", value1, value2, "relateOrder");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("remark is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("remark is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("remark =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("remark <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("remark >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("remark >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("remark <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("remark <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("remark like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("remark not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("remark in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("remark not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("remark between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("remark not between", value1, value2, "remark");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table detect_order
     *
     * @mbg.generated do_not_delete_during_merge Sun Apr 26 13:17:26 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table detect_order
     *
     * @mbg.generated Sun Apr 26 13:17:26 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}