package com.cloud.platform.model;

public class DetectOrder {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column detect_order.id
     *
     * @mbg.generated Sat Apr 25 17:58:34 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column detect_order.affiliation
     *
     * @mbg.generated Sat Apr 25 17:58:34 CST 2020
     */
    private String affiliation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column detect_order.order_index
     *
     * @mbg.generated Sat Apr 25 17:58:34 CST 2020
     */
    private String orderIndex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column detect_order.detect_date
     *
     * @mbg.generated Sat Apr 25 17:58:34 CST 2020
     */
    private String detectDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column detect_order.server
     *
     * @mbg.generated Sat Apr 25 17:58:34 CST 2020
     */
    private String server;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column detect_order.detect_member
     *
     * @mbg.generated Sat Apr 25 17:58:34 CST 2020
     */
    private String detectMember;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column detect_order.relate_order
     *
     * @mbg.generated Sat Apr 25 17:58:34 CST 2020
     */
    private String relateOrder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column detect_order.remark
     *
     * @mbg.generated Sat Apr 25 17:58:34 CST 2020
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column detect_order.id
     *
     * @return the value of detect_order.id
     *
     * @mbg.generated Sat Apr 25 17:58:34 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column detect_order.id
     *
     * @param id the value for detect_order.id
     *
     * @mbg.generated Sat Apr 25 17:58:34 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column detect_order.affiliation
     *
     * @return the value of detect_order.affiliation
     *
     * @mbg.generated Sat Apr 25 17:58:34 CST 2020
     */
    public String getAffiliation() {
        return affiliation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column detect_order.affiliation
     *
     * @param affiliation the value for detect_order.affiliation
     *
     * @mbg.generated Sat Apr 25 17:58:34 CST 2020
     */
    public void setAffiliation(String affiliation) {
        this.affiliation = affiliation == null ? null : affiliation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column detect_order.order_index
     *
     * @return the value of detect_order.order_index
     *
     * @mbg.generated Sat Apr 25 17:58:34 CST 2020
     */
    public String getOrderIndex() {
        return orderIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column detect_order.order_index
     *
     * @param orderIndex the value for detect_order.order_index
     *
     * @mbg.generated Sat Apr 25 17:58:34 CST 2020
     */
    public void setOrderIndex(String orderIndex) {
        this.orderIndex = orderIndex == null ? null : orderIndex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column detect_order.detect_date
     *
     * @return the value of detect_order.detect_date
     *
     * @mbg.generated Sat Apr 25 17:58:34 CST 2020
     */
    public String getDetectDate() {
        return detectDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column detect_order.detect_date
     *
     * @param detectDate the value for detect_order.detect_date
     *
     * @mbg.generated Sat Apr 25 17:58:34 CST 2020
     */
    public void setDetectDate(String detectDate) {
        this.detectDate = detectDate == null ? null : detectDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column detect_order.server
     *
     * @return the value of detect_order.server
     *
     * @mbg.generated Sat Apr 25 17:58:34 CST 2020
     */
    public String getServer() {
        return server;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column detect_order.server
     *
     * @param server the value for detect_order.server
     *
     * @mbg.generated Sat Apr 25 17:58:34 CST 2020
     */
    public void setServer(String server) {
        this.server = server == null ? null : server.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column detect_order.detect_member
     *
     * @return the value of detect_order.detect_member
     *
     * @mbg.generated Sat Apr 25 17:58:34 CST 2020
     */
    public String getDetectMember() {
        return detectMember;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column detect_order.detect_member
     *
     * @param detectMember the value for detect_order.detect_member
     *
     * @mbg.generated Sat Apr 25 17:58:34 CST 2020
     */
    public void setDetectMember(String detectMember) {
        this.detectMember = detectMember == null ? null : detectMember.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column detect_order.relate_order
     *
     * @return the value of detect_order.relate_order
     *
     * @mbg.generated Sat Apr 25 17:58:34 CST 2020
     */
    public String getRelateOrder() {
        return relateOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column detect_order.relate_order
     *
     * @param relateOrder the value for detect_order.relate_order
     *
     * @mbg.generated Sat Apr 25 17:58:34 CST 2020
     */
    public void setRelateOrder(String relateOrder) {
        this.relateOrder = relateOrder == null ? null : relateOrder.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column detect_order.remark
     *
     * @return the value of detect_order.remark
     *
     * @mbg.generated Sat Apr 25 17:58:34 CST 2020
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column detect_order.remark
     *
     * @param remark the value for detect_order.remark
     *
     * @mbg.generated Sat Apr 25 17:58:34 CST 2020
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}