package com.cloud.platform.model;

public class DeviceAssetGood {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_asset_goods.id
     *
     * @mbg.generated Sat Apr 25 17:58:35 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_asset_goods.affiliation
     *
     * @mbg.generated Sat Apr 25 17:58:35 CST 2020
     */
    private String affiliation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_asset_goods.device_name
     *
     * @mbg.generated Sat Apr 25 17:58:35 CST 2020
     */
    private String deviceName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_asset_goods.asset_code
     *
     * @mbg.generated Sat Apr 25 17:58:35 CST 2020
     */
    private String assetCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_asset_goods.classification
     *
     * @mbg.generated Sat Apr 25 17:58:35 CST 2020
     */
    private String classification;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_asset_goods.count
     *
     * @mbg.generated Sat Apr 25 17:58:35 CST 2020
     */
    private Integer count;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_asset_goods.manufacture
     *
     * @mbg.generated Sat Apr 25 17:58:35 CST 2020
     */
    private String manufacture;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_asset_goods.specification
     *
     * @mbg.generated Sat Apr 25 17:58:35 CST 2020
     */
    private String specification;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_asset_goods.product_date
     *
     * @mbg.generated Sat Apr 25 17:58:35 CST 2020
     */
    private String productDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_asset_goods.use_date
     *
     * @mbg.generated Sat Apr 25 17:58:35 CST 2020
     */
    private String useDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_asset_goods.service_life
     *
     * @mbg.generated Sat Apr 25 17:58:35 CST 2020
     */
    private Integer serviceLife;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_asset_goods.warranty_date
     *
     * @mbg.generated Sat Apr 25 17:58:35 CST 2020
     */
    private String warrantyDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_asset_goods.storage_location
     *
     * @mbg.generated Sat Apr 25 17:58:35 CST 2020
     */
    private String storageLocation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_asset_goods.storage_charge
     *
     * @mbg.generated Sat Apr 25 17:58:35 CST 2020
     */
    private String storageCharge;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_asset_goods.status
     *
     * @mbg.generated Sat Apr 25 17:58:35 CST 2020
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_asset_goods.unit
     *
     * @mbg.generated Sat Apr 25 17:58:35 CST 2020
     */
    private String unit;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_asset_goods.id
     *
     * @return the value of device_asset_goods.id
     *
     * @mbg.generated Sat Apr 25 17:58:35 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_asset_goods.id
     *
     * @param id the value for device_asset_goods.id
     *
     * @mbg.generated Sat Apr 25 17:58:35 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_asset_goods.affiliation
     *
     * @return the value of device_asset_goods.affiliation
     *
     * @mbg.generated Sat Apr 25 17:58:35 CST 2020
     */
    public String getAffiliation() {
        return affiliation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_asset_goods.affiliation
     *
     * @param affiliation the value for device_asset_goods.affiliation
     *
     * @mbg.generated Sat Apr 25 17:58:35 CST 2020
     */
    public void setAffiliation(String affiliation) {
        this.affiliation = affiliation == null ? null : affiliation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_asset_goods.device_name
     *
     * @return the value of device_asset_goods.device_name
     *
     * @mbg.generated Sat Apr 25 17:58:35 CST 2020
     */
    public String getDeviceName() {
        return deviceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_asset_goods.device_name
     *
     * @param deviceName the value for device_asset_goods.device_name
     *
     * @mbg.generated Sat Apr 25 17:58:35 CST 2020
     */
    public void setDeviceName(String deviceName) {
        this.deviceName = deviceName == null ? null : deviceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_asset_goods.asset_code
     *
     * @return the value of device_asset_goods.asset_code
     *
     * @mbg.generated Sat Apr 25 17:58:35 CST 2020
     */
    public String getAssetCode() {
        return assetCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_asset_goods.asset_code
     *
     * @param assetCode the value for device_asset_goods.asset_code
     *
     * @mbg.generated Sat Apr 25 17:58:35 CST 2020
     */
    public void setAssetCode(String assetCode) {
        this.assetCode = assetCode == null ? null : assetCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_asset_goods.classification
     *
     * @return the value of device_asset_goods.classification
     *
     * @mbg.generated Sat Apr 25 17:58:35 CST 2020
     */
    public String getClassification() {
        return classification;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_asset_goods.classification
     *
     * @param classification the value for device_asset_goods.classification
     *
     * @mbg.generated Sat Apr 25 17:58:35 CST 2020
     */
    public void setClassification(String classification) {
        this.classification = classification == null ? null : classification.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_asset_goods.count
     *
     * @return the value of device_asset_goods.count
     *
     * @mbg.generated Sat Apr 25 17:58:35 CST 2020
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_asset_goods.count
     *
     * @param count the value for device_asset_goods.count
     *
     * @mbg.generated Sat Apr 25 17:58:35 CST 2020
     */
    public void setCount(Integer count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_asset_goods.manufacture
     *
     * @return the value of device_asset_goods.manufacture
     *
     * @mbg.generated Sat Apr 25 17:58:35 CST 2020
     */
    public String getManufacture() {
        return manufacture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_asset_goods.manufacture
     *
     * @param manufacture the value for device_asset_goods.manufacture
     *
     * @mbg.generated Sat Apr 25 17:58:35 CST 2020
     */
    public void setManufacture(String manufacture) {
        this.manufacture = manufacture == null ? null : manufacture.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_asset_goods.specification
     *
     * @return the value of device_asset_goods.specification
     *
     * @mbg.generated Sat Apr 25 17:58:35 CST 2020
     */
    public String getSpecification() {
        return specification;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_asset_goods.specification
     *
     * @param specification the value for device_asset_goods.specification
     *
     * @mbg.generated Sat Apr 25 17:58:35 CST 2020
     */
    public void setSpecification(String specification) {
        this.specification = specification == null ? null : specification.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_asset_goods.product_date
     *
     * @return the value of device_asset_goods.product_date
     *
     * @mbg.generated Sat Apr 25 17:58:35 CST 2020
     */
    public String getProductDate() {
        return productDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_asset_goods.product_date
     *
     * @param productDate the value for device_asset_goods.product_date
     *
     * @mbg.generated Sat Apr 25 17:58:35 CST 2020
     */
    public void setProductDate(String productDate) {
        this.productDate = productDate == null ? null : productDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_asset_goods.use_date
     *
     * @return the value of device_asset_goods.use_date
     *
     * @mbg.generated Sat Apr 25 17:58:35 CST 2020
     */
    public String getUseDate() {
        return useDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_asset_goods.use_date
     *
     * @param useDate the value for device_asset_goods.use_date
     *
     * @mbg.generated Sat Apr 25 17:58:35 CST 2020
     */
    public void setUseDate(String useDate) {
        this.useDate = useDate == null ? null : useDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_asset_goods.service_life
     *
     * @return the value of device_asset_goods.service_life
     *
     * @mbg.generated Sat Apr 25 17:58:35 CST 2020
     */
    public Integer getServiceLife() {
        return serviceLife;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_asset_goods.service_life
     *
     * @param serviceLife the value for device_asset_goods.service_life
     *
     * @mbg.generated Sat Apr 25 17:58:35 CST 2020
     */
    public void setServiceLife(Integer serviceLife) {
        this.serviceLife = serviceLife;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_asset_goods.warranty_date
     *
     * @return the value of device_asset_goods.warranty_date
     *
     * @mbg.generated Sat Apr 25 17:58:35 CST 2020
     */
    public String getWarrantyDate() {
        return warrantyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_asset_goods.warranty_date
     *
     * @param warrantyDate the value for device_asset_goods.warranty_date
     *
     * @mbg.generated Sat Apr 25 17:58:35 CST 2020
     */
    public void setWarrantyDate(String warrantyDate) {
        this.warrantyDate = warrantyDate == null ? null : warrantyDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_asset_goods.storage_location
     *
     * @return the value of device_asset_goods.storage_location
     *
     * @mbg.generated Sat Apr 25 17:58:35 CST 2020
     */
    public String getStorageLocation() {
        return storageLocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_asset_goods.storage_location
     *
     * @param storageLocation the value for device_asset_goods.storage_location
     *
     * @mbg.generated Sat Apr 25 17:58:35 CST 2020
     */
    public void setStorageLocation(String storageLocation) {
        this.storageLocation = storageLocation == null ? null : storageLocation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_asset_goods.storage_charge
     *
     * @return the value of device_asset_goods.storage_charge
     *
     * @mbg.generated Sat Apr 25 17:58:35 CST 2020
     */
    public String getStorageCharge() {
        return storageCharge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_asset_goods.storage_charge
     *
     * @param storageCharge the value for device_asset_goods.storage_charge
     *
     * @mbg.generated Sat Apr 25 17:58:35 CST 2020
     */
    public void setStorageCharge(String storageCharge) {
        this.storageCharge = storageCharge == null ? null : storageCharge.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_asset_goods.status
     *
     * @return the value of device_asset_goods.status
     *
     * @mbg.generated Sat Apr 25 17:58:35 CST 2020
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_asset_goods.status
     *
     * @param status the value for device_asset_goods.status
     *
     * @mbg.generated Sat Apr 25 17:58:35 CST 2020
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_asset_goods.unit
     *
     * @return the value of device_asset_goods.unit
     *
     * @mbg.generated Sat Apr 25 17:58:35 CST 2020
     */
    public String getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_asset_goods.unit
     *
     * @param unit the value for device_asset_goods.unit
     *
     * @mbg.generated Sat Apr 25 17:58:35 CST 2020
     */
    public void setUnit(String unit) {
        this.unit = unit == null ? null : unit.trim();
    }
}