package com.cloud.platform.model;

public class DeviceClassification {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_classification.id
     *
     * @mbg.generated Wed Apr 22 18:35:09 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_classification.classification
     *
     * @mbg.generated Wed Apr 22 18:35:09 CST 2020
     */
    private String classification;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_classification.classification_code
     *
     * @mbg.generated Wed Apr 22 18:35:09 CST 2020
     */
    private String classificationCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_classification.level
     *
     * @mbg.generated Wed Apr 22 18:35:09 CST 2020
     */
    private Integer level;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_classification.id
     *
     * @return the value of device_classification.id
     *
     * @mbg.generated Wed Apr 22 18:35:09 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_classification.id
     *
     * @param id the value for device_classification.id
     *
     * @mbg.generated Wed Apr 22 18:35:09 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_classification.classification
     *
     * @return the value of device_classification.classification
     *
     * @mbg.generated Wed Apr 22 18:35:09 CST 2020
     */
    public String getClassification() {
        return classification;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_classification.classification
     *
     * @param classification the value for device_classification.classification
     *
     * @mbg.generated Wed Apr 22 18:35:09 CST 2020
     */
    public void setClassification(String classification) {
        this.classification = classification == null ? null : classification.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_classification.classification_code
     *
     * @return the value of device_classification.classification_code
     *
     * @mbg.generated Wed Apr 22 18:35:09 CST 2020
     */
    public String getClassificationCode() {
        return classificationCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_classification.classification_code
     *
     * @param classificationCode the value for device_classification.classification_code
     *
     * @mbg.generated Wed Apr 22 18:35:09 CST 2020
     */
    public void setClassificationCode(String classificationCode) {
        this.classificationCode = classificationCode == null ? null : classificationCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_classification.level
     *
     * @return the value of device_classification.level
     *
     * @mbg.generated Wed Apr 22 18:35:09 CST 2020
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_classification.level
     *
     * @param level the value for device_classification.level
     *
     * @mbg.generated Wed Apr 22 18:35:09 CST 2020
     */
    public void setLevel(Integer level) {
        this.level = level;
    }
}