package com.cloud.platform.model;

import java.util.Date;

public class DeviceErrorCode {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_error_code.id
     *
     * @mbg.generated Tue Apr 14 13:57:25 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_error_code.classification
     *
     * @mbg.generated Tue Apr 14 13:57:25 CST 2020
     */
    private String classification;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_error_code.error_code
     *
     * @mbg.generated Tue Apr 14 13:57:25 CST 2020
     */
    private String errorCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_error_code.description
     *
     * @mbg.generated Tue Apr 14 13:57:25 CST 2020
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_error_code.create_time
     *
     * @mbg.generated Tue Apr 14 13:57:25 CST 2020
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_error_code.id
     *
     * @return the value of device_error_code.id
     *
     * @mbg.generated Tue Apr 14 13:57:25 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_error_code.id
     *
     * @param id the value for device_error_code.id
     *
     * @mbg.generated Tue Apr 14 13:57:25 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_error_code.classification
     *
     * @return the value of device_error_code.classification
     *
     * @mbg.generated Tue Apr 14 13:57:25 CST 2020
     */
    public String getClassification() {
        return classification;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_error_code.classification
     *
     * @param classification the value for device_error_code.classification
     *
     * @mbg.generated Tue Apr 14 13:57:25 CST 2020
     */
    public void setClassification(String classification) {
        this.classification = classification == null ? null : classification.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_error_code.error_code
     *
     * @return the value of device_error_code.error_code
     *
     * @mbg.generated Tue Apr 14 13:57:25 CST 2020
     */
    public String getErrorCode() {
        return errorCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_error_code.error_code
     *
     * @param errorCode the value for device_error_code.error_code
     *
     * @mbg.generated Tue Apr 14 13:57:25 CST 2020
     */
    public void setErrorCode(String errorCode) {
        this.errorCode = errorCode == null ? null : errorCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_error_code.description
     *
     * @return the value of device_error_code.description
     *
     * @mbg.generated Tue Apr 14 13:57:25 CST 2020
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_error_code.description
     *
     * @param description the value for device_error_code.description
     *
     * @mbg.generated Tue Apr 14 13:57:25 CST 2020
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_error_code.create_time
     *
     * @return the value of device_error_code.create_time
     *
     * @mbg.generated Tue Apr 14 13:57:25 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_error_code.create_time
     *
     * @param createTime the value for device_error_code.create_time
     *
     * @mbg.generated Tue Apr 14 13:57:25 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}