package com.cloud.platform.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class ServerInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table servers_info
     *
     * @mbg.generated Tue Apr 14 13:57:25 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table servers_info
     *
     * @mbg.generated Tue Apr 14 13:57:25 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table servers_info
     *
     * @mbg.generated Tue Apr 14 13:57:25 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table servers_info
     *
     * @mbg.generated Tue Apr 14 13:57:25 CST 2020
     */
    public ServerInfoExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table servers_info
     *
     * @mbg.generated Tue Apr 14 13:57:25 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table servers_info
     *
     * @mbg.generated Tue Apr 14 13:57:25 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table servers_info
     *
     * @mbg.generated Tue Apr 14 13:57:25 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table servers_info
     *
     * @mbg.generated Tue Apr 14 13:57:25 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table servers_info
     *
     * @mbg.generated Tue Apr 14 13:57:25 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table servers_info
     *
     * @mbg.generated Tue Apr 14 13:57:25 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table servers_info
     *
     * @mbg.generated Tue Apr 14 13:57:25 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table servers_info
     *
     * @mbg.generated Tue Apr 14 13:57:25 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table servers_info
     *
     * @mbg.generated Tue Apr 14 13:57:25 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table servers_info
     *
     * @mbg.generated Tue Apr 14 13:57:25 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table servers_info
     *
     * @mbg.generated Tue Apr 14 13:57:25 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdentiferIsNull() {
            addCriterion("identifer is null");
            return (Criteria) this;
        }

        public Criteria andIdentiferIsNotNull() {
            addCriterion("identifer is not null");
            return (Criteria) this;
        }

        public Criteria andIdentiferEqualTo(String value) {
            addCriterion("identifer =", value, "identifer");
            return (Criteria) this;
        }

        public Criteria andIdentiferNotEqualTo(String value) {
            addCriterion("identifer <>", value, "identifer");
            return (Criteria) this;
        }

        public Criteria andIdentiferGreaterThan(String value) {
            addCriterion("identifer >", value, "identifer");
            return (Criteria) this;
        }

        public Criteria andIdentiferGreaterThanOrEqualTo(String value) {
            addCriterion("identifer >=", value, "identifer");
            return (Criteria) this;
        }

        public Criteria andIdentiferLessThan(String value) {
            addCriterion("identifer <", value, "identifer");
            return (Criteria) this;
        }

        public Criteria andIdentiferLessThanOrEqualTo(String value) {
            addCriterion("identifer <=", value, "identifer");
            return (Criteria) this;
        }

        public Criteria andIdentiferLike(String value) {
            addCriterion("identifer like", value, "identifer");
            return (Criteria) this;
        }

        public Criteria andIdentiferNotLike(String value) {
            addCriterion("identifer not like", value, "identifer");
            return (Criteria) this;
        }

        public Criteria andIdentiferIn(List<String> values) {
            addCriterion("identifer in", values, "identifer");
            return (Criteria) this;
        }

        public Criteria andIdentiferNotIn(List<String> values) {
            addCriterion("identifer not in", values, "identifer");
            return (Criteria) this;
        }

        public Criteria andIdentiferBetween(String value1, String value2) {
            addCriterion("identifer between", value1, value2, "identifer");
            return (Criteria) this;
        }

        public Criteria andIdentiferNotBetween(String value1, String value2) {
            addCriterion("identifer not between", value1, value2, "identifer");
            return (Criteria) this;
        }

        public Criteria andServerNameIsNull() {
            addCriterion("server_name is null");
            return (Criteria) this;
        }

        public Criteria andServerNameIsNotNull() {
            addCriterion("server_name is not null");
            return (Criteria) this;
        }

        public Criteria andServerNameEqualTo(String value) {
            addCriterion("server_name =", value, "serverName");
            return (Criteria) this;
        }

        public Criteria andServerNameNotEqualTo(String value) {
            addCriterion("server_name <>", value, "serverName");
            return (Criteria) this;
        }

        public Criteria andServerNameGreaterThan(String value) {
            addCriterion("server_name >", value, "serverName");
            return (Criteria) this;
        }

        public Criteria andServerNameGreaterThanOrEqualTo(String value) {
            addCriterion("server_name >=", value, "serverName");
            return (Criteria) this;
        }

        public Criteria andServerNameLessThan(String value) {
            addCriterion("server_name <", value, "serverName");
            return (Criteria) this;
        }

        public Criteria andServerNameLessThanOrEqualTo(String value) {
            addCriterion("server_name <=", value, "serverName");
            return (Criteria) this;
        }

        public Criteria andServerNameLike(String value) {
            addCriterion("server_name like", value, "serverName");
            return (Criteria) this;
        }

        public Criteria andServerNameNotLike(String value) {
            addCriterion("server_name not like", value, "serverName");
            return (Criteria) this;
        }

        public Criteria andServerNameIn(List<String> values) {
            addCriterion("server_name in", values, "serverName");
            return (Criteria) this;
        }

        public Criteria andServerNameNotIn(List<String> values) {
            addCriterion("server_name not in", values, "serverName");
            return (Criteria) this;
        }

        public Criteria andServerNameBetween(String value1, String value2) {
            addCriterion("server_name between", value1, value2, "serverName");
            return (Criteria) this;
        }

        public Criteria andServerNameNotBetween(String value1, String value2) {
            addCriterion("server_name not between", value1, value2, "serverName");
            return (Criteria) this;
        }

        public Criteria andAbbreviationIsNull() {
            addCriterion("abbreviation is null");
            return (Criteria) this;
        }

        public Criteria andAbbreviationIsNotNull() {
            addCriterion("abbreviation is not null");
            return (Criteria) this;
        }

        public Criteria andAbbreviationEqualTo(String value) {
            addCriterion("abbreviation =", value, "abbreviation");
            return (Criteria) this;
        }

        public Criteria andAbbreviationNotEqualTo(String value) {
            addCriterion("abbreviation <>", value, "abbreviation");
            return (Criteria) this;
        }

        public Criteria andAbbreviationGreaterThan(String value) {
            addCriterion("abbreviation >", value, "abbreviation");
            return (Criteria) this;
        }

        public Criteria andAbbreviationGreaterThanOrEqualTo(String value) {
            addCriterion("abbreviation >=", value, "abbreviation");
            return (Criteria) this;
        }

        public Criteria andAbbreviationLessThan(String value) {
            addCriterion("abbreviation <", value, "abbreviation");
            return (Criteria) this;
        }

        public Criteria andAbbreviationLessThanOrEqualTo(String value) {
            addCriterion("abbreviation <=", value, "abbreviation");
            return (Criteria) this;
        }

        public Criteria andAbbreviationLike(String value) {
            addCriterion("abbreviation like", value, "abbreviation");
            return (Criteria) this;
        }

        public Criteria andAbbreviationNotLike(String value) {
            addCriterion("abbreviation not like", value, "abbreviation");
            return (Criteria) this;
        }

        public Criteria andAbbreviationIn(List<String> values) {
            addCriterion("abbreviation in", values, "abbreviation");
            return (Criteria) this;
        }

        public Criteria andAbbreviationNotIn(List<String> values) {
            addCriterion("abbreviation not in", values, "abbreviation");
            return (Criteria) this;
        }

        public Criteria andAbbreviationBetween(String value1, String value2) {
            addCriterion("abbreviation between", value1, value2, "abbreviation");
            return (Criteria) this;
        }

        public Criteria andAbbreviationNotBetween(String value1, String value2) {
            addCriterion("abbreviation not between", value1, value2, "abbreviation");
            return (Criteria) this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("type is null");
            return (Criteria) this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("type is not null");
            return (Criteria) this;
        }

        public Criteria andTypeEqualTo(String value) {
            addCriterion("type =", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotEqualTo(String value) {
            addCriterion("type <>", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThan(String value) {
            addCriterion("type >", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(String value) {
            addCriterion("type >=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThan(String value) {
            addCriterion("type <", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThanOrEqualTo(String value) {
            addCriterion("type <=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLike(String value) {
            addCriterion("type like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotLike(String value) {
            addCriterion("type not like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeIn(List<String> values) {
            addCriterion("type in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotIn(List<String> values) {
            addCriterion("type not in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeBetween(String value1, String value2) {
            addCriterion("type between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotBetween(String value1, String value2) {
            addCriterion("type not between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andCreditCodeIsNull() {
            addCriterion("credit_code is null");
            return (Criteria) this;
        }

        public Criteria andCreditCodeIsNotNull() {
            addCriterion("credit_code is not null");
            return (Criteria) this;
        }

        public Criteria andCreditCodeEqualTo(Integer value) {
            addCriterion("credit_code =", value, "creditCode");
            return (Criteria) this;
        }

        public Criteria andCreditCodeNotEqualTo(Integer value) {
            addCriterion("credit_code <>", value, "creditCode");
            return (Criteria) this;
        }

        public Criteria andCreditCodeGreaterThan(Integer value) {
            addCriterion("credit_code >", value, "creditCode");
            return (Criteria) this;
        }

        public Criteria andCreditCodeGreaterThanOrEqualTo(Integer value) {
            addCriterion("credit_code >=", value, "creditCode");
            return (Criteria) this;
        }

        public Criteria andCreditCodeLessThan(Integer value) {
            addCriterion("credit_code <", value, "creditCode");
            return (Criteria) this;
        }

        public Criteria andCreditCodeLessThanOrEqualTo(Integer value) {
            addCriterion("credit_code <=", value, "creditCode");
            return (Criteria) this;
        }

        public Criteria andCreditCodeIn(List<Integer> values) {
            addCriterion("credit_code in", values, "creditCode");
            return (Criteria) this;
        }

        public Criteria andCreditCodeNotIn(List<Integer> values) {
            addCriterion("credit_code not in", values, "creditCode");
            return (Criteria) this;
        }

        public Criteria andCreditCodeBetween(Integer value1, Integer value2) {
            addCriterion("credit_code between", value1, value2, "creditCode");
            return (Criteria) this;
        }

        public Criteria andCreditCodeNotBetween(Integer value1, Integer value2) {
            addCriterion("credit_code not between", value1, value2, "creditCode");
            return (Criteria) this;
        }

        public Criteria andLocationIsNull() {
            addCriterion("location is null");
            return (Criteria) this;
        }

        public Criteria andLocationIsNotNull() {
            addCriterion("location is not null");
            return (Criteria) this;
        }

        public Criteria andLocationEqualTo(String value) {
            addCriterion("location =", value, "location");
            return (Criteria) this;
        }

        public Criteria andLocationNotEqualTo(String value) {
            addCriterion("location <>", value, "location");
            return (Criteria) this;
        }

        public Criteria andLocationGreaterThan(String value) {
            addCriterion("location >", value, "location");
            return (Criteria) this;
        }

        public Criteria andLocationGreaterThanOrEqualTo(String value) {
            addCriterion("location >=", value, "location");
            return (Criteria) this;
        }

        public Criteria andLocationLessThan(String value) {
            addCriterion("location <", value, "location");
            return (Criteria) this;
        }

        public Criteria andLocationLessThanOrEqualTo(String value) {
            addCriterion("location <=", value, "location");
            return (Criteria) this;
        }

        public Criteria andLocationLike(String value) {
            addCriterion("location like", value, "location");
            return (Criteria) this;
        }

        public Criteria andLocationNotLike(String value) {
            addCriterion("location not like", value, "location");
            return (Criteria) this;
        }

        public Criteria andLocationIn(List<String> values) {
            addCriterion("location in", values, "location");
            return (Criteria) this;
        }

        public Criteria andLocationNotIn(List<String> values) {
            addCriterion("location not in", values, "location");
            return (Criteria) this;
        }

        public Criteria andLocationBetween(String value1, String value2) {
            addCriterion("location between", value1, value2, "location");
            return (Criteria) this;
        }

        public Criteria andLocationNotBetween(String value1, String value2) {
            addCriterion("location not between", value1, value2, "location");
            return (Criteria) this;
        }

        public Criteria andPresentIsNull() {
            addCriterion("present is null");
            return (Criteria) this;
        }

        public Criteria andPresentIsNotNull() {
            addCriterion("present is not null");
            return (Criteria) this;
        }

        public Criteria andPresentEqualTo(String value) {
            addCriterion("present =", value, "present");
            return (Criteria) this;
        }

        public Criteria andPresentNotEqualTo(String value) {
            addCriterion("present <>", value, "present");
            return (Criteria) this;
        }

        public Criteria andPresentGreaterThan(String value) {
            addCriterion("present >", value, "present");
            return (Criteria) this;
        }

        public Criteria andPresentGreaterThanOrEqualTo(String value) {
            addCriterion("present >=", value, "present");
            return (Criteria) this;
        }

        public Criteria andPresentLessThan(String value) {
            addCriterion("present <", value, "present");
            return (Criteria) this;
        }

        public Criteria andPresentLessThanOrEqualTo(String value) {
            addCriterion("present <=", value, "present");
            return (Criteria) this;
        }

        public Criteria andPresentLike(String value) {
            addCriterion("present like", value, "present");
            return (Criteria) this;
        }

        public Criteria andPresentNotLike(String value) {
            addCriterion("present not like", value, "present");
            return (Criteria) this;
        }

        public Criteria andPresentIn(List<String> values) {
            addCriterion("present in", values, "present");
            return (Criteria) this;
        }

        public Criteria andPresentNotIn(List<String> values) {
            addCriterion("present not in", values, "present");
            return (Criteria) this;
        }

        public Criteria andPresentBetween(String value1, String value2) {
            addCriterion("present between", value1, value2, "present");
            return (Criteria) this;
        }

        public Criteria andPresentNotBetween(String value1, String value2) {
            addCriterion("present not between", value1, value2, "present");
            return (Criteria) this;
        }

        public Criteria andRegisteredCapitalIsNull() {
            addCriterion("registered_capital is null");
            return (Criteria) this;
        }

        public Criteria andRegisteredCapitalIsNotNull() {
            addCriterion("registered_capital is not null");
            return (Criteria) this;
        }

        public Criteria andRegisteredCapitalEqualTo(Integer value) {
            addCriterion("registered_capital =", value, "registeredCapital");
            return (Criteria) this;
        }

        public Criteria andRegisteredCapitalNotEqualTo(Integer value) {
            addCriterion("registered_capital <>", value, "registeredCapital");
            return (Criteria) this;
        }

        public Criteria andRegisteredCapitalGreaterThan(Integer value) {
            addCriterion("registered_capital >", value, "registeredCapital");
            return (Criteria) this;
        }

        public Criteria andRegisteredCapitalGreaterThanOrEqualTo(Integer value) {
            addCriterion("registered_capital >=", value, "registeredCapital");
            return (Criteria) this;
        }

        public Criteria andRegisteredCapitalLessThan(Integer value) {
            addCriterion("registered_capital <", value, "registeredCapital");
            return (Criteria) this;
        }

        public Criteria andRegisteredCapitalLessThanOrEqualTo(Integer value) {
            addCriterion("registered_capital <=", value, "registeredCapital");
            return (Criteria) this;
        }

        public Criteria andRegisteredCapitalIn(List<Integer> values) {
            addCriterion("registered_capital in", values, "registeredCapital");
            return (Criteria) this;
        }

        public Criteria andRegisteredCapitalNotIn(List<Integer> values) {
            addCriterion("registered_capital not in", values, "registeredCapital");
            return (Criteria) this;
        }

        public Criteria andRegisteredCapitalBetween(Integer value1, Integer value2) {
            addCriterion("registered_capital between", value1, value2, "registeredCapital");
            return (Criteria) this;
        }

        public Criteria andRegisteredCapitalNotBetween(Integer value1, Integer value2) {
            addCriterion("registered_capital not between", value1, value2, "registeredCapital");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterionForJDBCDate("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterionForJDBCDate("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterionForJDBCDate("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterionForJDBCDate("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterionForJDBCDate("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterionForJDBCDate("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andManageRangeIsNull() {
            addCriterion("manage_range is null");
            return (Criteria) this;
        }

        public Criteria andManageRangeIsNotNull() {
            addCriterion("manage_range is not null");
            return (Criteria) this;
        }

        public Criteria andManageRangeEqualTo(String value) {
            addCriterion("manage_range =", value, "manageRange");
            return (Criteria) this;
        }

        public Criteria andManageRangeNotEqualTo(String value) {
            addCriterion("manage_range <>", value, "manageRange");
            return (Criteria) this;
        }

        public Criteria andManageRangeGreaterThan(String value) {
            addCriterion("manage_range >", value, "manageRange");
            return (Criteria) this;
        }

        public Criteria andManageRangeGreaterThanOrEqualTo(String value) {
            addCriterion("manage_range >=", value, "manageRange");
            return (Criteria) this;
        }

        public Criteria andManageRangeLessThan(String value) {
            addCriterion("manage_range <", value, "manageRange");
            return (Criteria) this;
        }

        public Criteria andManageRangeLessThanOrEqualTo(String value) {
            addCriterion("manage_range <=", value, "manageRange");
            return (Criteria) this;
        }

        public Criteria andManageRangeLike(String value) {
            addCriterion("manage_range like", value, "manageRange");
            return (Criteria) this;
        }

        public Criteria andManageRangeNotLike(String value) {
            addCriterion("manage_range not like", value, "manageRange");
            return (Criteria) this;
        }

        public Criteria andManageRangeIn(List<String> values) {
            addCriterion("manage_range in", values, "manageRange");
            return (Criteria) this;
        }

        public Criteria andManageRangeNotIn(List<String> values) {
            addCriterion("manage_range not in", values, "manageRange");
            return (Criteria) this;
        }

        public Criteria andManageRangeBetween(String value1, String value2) {
            addCriterion("manage_range between", value1, value2, "manageRange");
            return (Criteria) this;
        }

        public Criteria andManageRangeNotBetween(String value1, String value2) {
            addCriterion("manage_range not between", value1, value2, "manageRange");
            return (Criteria) this;
        }

        public Criteria andManageBegintimeIsNull() {
            addCriterion("manage_begintime is null");
            return (Criteria) this;
        }

        public Criteria andManageBegintimeIsNotNull() {
            addCriterion("manage_begintime is not null");
            return (Criteria) this;
        }

        public Criteria andManageBegintimeEqualTo(Date value) {
            addCriterionForJDBCDate("manage_begintime =", value, "manageBegintime");
            return (Criteria) this;
        }

        public Criteria andManageBegintimeNotEqualTo(Date value) {
            addCriterionForJDBCDate("manage_begintime <>", value, "manageBegintime");
            return (Criteria) this;
        }

        public Criteria andManageBegintimeGreaterThan(Date value) {
            addCriterionForJDBCDate("manage_begintime >", value, "manageBegintime");
            return (Criteria) this;
        }

        public Criteria andManageBegintimeGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("manage_begintime >=", value, "manageBegintime");
            return (Criteria) this;
        }

        public Criteria andManageBegintimeLessThan(Date value) {
            addCriterionForJDBCDate("manage_begintime <", value, "manageBegintime");
            return (Criteria) this;
        }

        public Criteria andManageBegintimeLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("manage_begintime <=", value, "manageBegintime");
            return (Criteria) this;
        }

        public Criteria andManageBegintimeIn(List<Date> values) {
            addCriterionForJDBCDate("manage_begintime in", values, "manageBegintime");
            return (Criteria) this;
        }

        public Criteria andManageBegintimeNotIn(List<Date> values) {
            addCriterionForJDBCDate("manage_begintime not in", values, "manageBegintime");
            return (Criteria) this;
        }

        public Criteria andManageBegintimeBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("manage_begintime between", value1, value2, "manageBegintime");
            return (Criteria) this;
        }

        public Criteria andManageBegintimeNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("manage_begintime not between", value1, value2, "manageBegintime");
            return (Criteria) this;
        }

        public Criteria andManageEndtimeIsNull() {
            addCriterion("manage_endtime is null");
            return (Criteria) this;
        }

        public Criteria andManageEndtimeIsNotNull() {
            addCriterion("manage_endtime is not null");
            return (Criteria) this;
        }

        public Criteria andManageEndtimeEqualTo(Date value) {
            addCriterionForJDBCDate("manage_endtime =", value, "manageEndtime");
            return (Criteria) this;
        }

        public Criteria andManageEndtimeNotEqualTo(Date value) {
            addCriterionForJDBCDate("manage_endtime <>", value, "manageEndtime");
            return (Criteria) this;
        }

        public Criteria andManageEndtimeGreaterThan(Date value) {
            addCriterionForJDBCDate("manage_endtime >", value, "manageEndtime");
            return (Criteria) this;
        }

        public Criteria andManageEndtimeGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("manage_endtime >=", value, "manageEndtime");
            return (Criteria) this;
        }

        public Criteria andManageEndtimeLessThan(Date value) {
            addCriterionForJDBCDate("manage_endtime <", value, "manageEndtime");
            return (Criteria) this;
        }

        public Criteria andManageEndtimeLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("manage_endtime <=", value, "manageEndtime");
            return (Criteria) this;
        }

        public Criteria andManageEndtimeIn(List<Date> values) {
            addCriterionForJDBCDate("manage_endtime in", values, "manageEndtime");
            return (Criteria) this;
        }

        public Criteria andManageEndtimeNotIn(List<Date> values) {
            addCriterionForJDBCDate("manage_endtime not in", values, "manageEndtime");
            return (Criteria) this;
        }

        public Criteria andManageEndtimeBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("manage_endtime between", value1, value2, "manageEndtime");
            return (Criteria) this;
        }

        public Criteria andManageEndtimeNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("manage_endtime not between", value1, value2, "manageEndtime");
            return (Criteria) this;
        }

        public Criteria andRegistrarIsNull() {
            addCriterion("registrar is null");
            return (Criteria) this;
        }

        public Criteria andRegistrarIsNotNull() {
            addCriterion("registrar is not null");
            return (Criteria) this;
        }

        public Criteria andRegistrarEqualTo(String value) {
            addCriterion("registrar =", value, "registrar");
            return (Criteria) this;
        }

        public Criteria andRegistrarNotEqualTo(String value) {
            addCriterion("registrar <>", value, "registrar");
            return (Criteria) this;
        }

        public Criteria andRegistrarGreaterThan(String value) {
            addCriterion("registrar >", value, "registrar");
            return (Criteria) this;
        }

        public Criteria andRegistrarGreaterThanOrEqualTo(String value) {
            addCriterion("registrar >=", value, "registrar");
            return (Criteria) this;
        }

        public Criteria andRegistrarLessThan(String value) {
            addCriterion("registrar <", value, "registrar");
            return (Criteria) this;
        }

        public Criteria andRegistrarLessThanOrEqualTo(String value) {
            addCriterion("registrar <=", value, "registrar");
            return (Criteria) this;
        }

        public Criteria andRegistrarLike(String value) {
            addCriterion("registrar like", value, "registrar");
            return (Criteria) this;
        }

        public Criteria andRegistrarNotLike(String value) {
            addCriterion("registrar not like", value, "registrar");
            return (Criteria) this;
        }

        public Criteria andRegistrarIn(List<String> values) {
            addCriterion("registrar in", values, "registrar");
            return (Criteria) this;
        }

        public Criteria andRegistrarNotIn(List<String> values) {
            addCriterion("registrar not in", values, "registrar");
            return (Criteria) this;
        }

        public Criteria andRegistrarBetween(String value1, String value2) {
            addCriterion("registrar between", value1, value2, "registrar");
            return (Criteria) this;
        }

        public Criteria andRegistrarNotBetween(String value1, String value2) {
            addCriterion("registrar not between", value1, value2, "registrar");
            return (Criteria) this;
        }

        public Criteria andIssueTimeIsNull() {
            addCriterion("issue_time is null");
            return (Criteria) this;
        }

        public Criteria andIssueTimeIsNotNull() {
            addCriterion("issue_time is not null");
            return (Criteria) this;
        }

        public Criteria andIssueTimeEqualTo(Date value) {
            addCriterionForJDBCDate("issue_time =", value, "issueTime");
            return (Criteria) this;
        }

        public Criteria andIssueTimeNotEqualTo(Date value) {
            addCriterionForJDBCDate("issue_time <>", value, "issueTime");
            return (Criteria) this;
        }

        public Criteria andIssueTimeGreaterThan(Date value) {
            addCriterionForJDBCDate("issue_time >", value, "issueTime");
            return (Criteria) this;
        }

        public Criteria andIssueTimeGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("issue_time >=", value, "issueTime");
            return (Criteria) this;
        }

        public Criteria andIssueTimeLessThan(Date value) {
            addCriterionForJDBCDate("issue_time <", value, "issueTime");
            return (Criteria) this;
        }

        public Criteria andIssueTimeLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("issue_time <=", value, "issueTime");
            return (Criteria) this;
        }

        public Criteria andIssueTimeIn(List<Date> values) {
            addCriterionForJDBCDate("issue_time in", values, "issueTime");
            return (Criteria) this;
        }

        public Criteria andIssueTimeNotIn(List<Date> values) {
            addCriterionForJDBCDate("issue_time not in", values, "issueTime");
            return (Criteria) this;
        }

        public Criteria andIssueTimeBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("issue_time between", value1, value2, "issueTime");
            return (Criteria) this;
        }

        public Criteria andIssueTimeNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("issue_time not between", value1, value2, "issueTime");
            return (Criteria) this;
        }

        public Criteria andPrincipalIsNull() {
            addCriterion("principal is null");
            return (Criteria) this;
        }

        public Criteria andPrincipalIsNotNull() {
            addCriterion("principal is not null");
            return (Criteria) this;
        }

        public Criteria andPrincipalEqualTo(String value) {
            addCriterion("principal =", value, "principal");
            return (Criteria) this;
        }

        public Criteria andPrincipalNotEqualTo(String value) {
            addCriterion("principal <>", value, "principal");
            return (Criteria) this;
        }

        public Criteria andPrincipalGreaterThan(String value) {
            addCriterion("principal >", value, "principal");
            return (Criteria) this;
        }

        public Criteria andPrincipalGreaterThanOrEqualTo(String value) {
            addCriterion("principal >=", value, "principal");
            return (Criteria) this;
        }

        public Criteria andPrincipalLessThan(String value) {
            addCriterion("principal <", value, "principal");
            return (Criteria) this;
        }

        public Criteria andPrincipalLessThanOrEqualTo(String value) {
            addCriterion("principal <=", value, "principal");
            return (Criteria) this;
        }

        public Criteria andPrincipalLike(String value) {
            addCriterion("principal like", value, "principal");
            return (Criteria) this;
        }

        public Criteria andPrincipalNotLike(String value) {
            addCriterion("principal not like", value, "principal");
            return (Criteria) this;
        }

        public Criteria andPrincipalIn(List<String> values) {
            addCriterion("principal in", values, "principal");
            return (Criteria) this;
        }

        public Criteria andPrincipalNotIn(List<String> values) {
            addCriterion("principal not in", values, "principal");
            return (Criteria) this;
        }

        public Criteria andPrincipalBetween(String value1, String value2) {
            addCriterion("principal between", value1, value2, "principal");
            return (Criteria) this;
        }

        public Criteria andPrincipalNotBetween(String value1, String value2) {
            addCriterion("principal not between", value1, value2, "principal");
            return (Criteria) this;
        }

        public Criteria andPrincipalContactInfoIsNull() {
            addCriterion("principal_contact_info is null");
            return (Criteria) this;
        }

        public Criteria andPrincipalContactInfoIsNotNull() {
            addCriterion("principal_contact_info is not null");
            return (Criteria) this;
        }

        public Criteria andPrincipalContactInfoEqualTo(String value) {
            addCriterion("principal_contact_info =", value, "principalContactInfo");
            return (Criteria) this;
        }

        public Criteria andPrincipalContactInfoNotEqualTo(String value) {
            addCriterion("principal_contact_info <>", value, "principalContactInfo");
            return (Criteria) this;
        }

        public Criteria andPrincipalContactInfoGreaterThan(String value) {
            addCriterion("principal_contact_info >", value, "principalContactInfo");
            return (Criteria) this;
        }

        public Criteria andPrincipalContactInfoGreaterThanOrEqualTo(String value) {
            addCriterion("principal_contact_info >=", value, "principalContactInfo");
            return (Criteria) this;
        }

        public Criteria andPrincipalContactInfoLessThan(String value) {
            addCriterion("principal_contact_info <", value, "principalContactInfo");
            return (Criteria) this;
        }

        public Criteria andPrincipalContactInfoLessThanOrEqualTo(String value) {
            addCriterion("principal_contact_info <=", value, "principalContactInfo");
            return (Criteria) this;
        }

        public Criteria andPrincipalContactInfoLike(String value) {
            addCriterion("principal_contact_info like", value, "principalContactInfo");
            return (Criteria) this;
        }

        public Criteria andPrincipalContactInfoNotLike(String value) {
            addCriterion("principal_contact_info not like", value, "principalContactInfo");
            return (Criteria) this;
        }

        public Criteria andPrincipalContactInfoIn(List<String> values) {
            addCriterion("principal_contact_info in", values, "principalContactInfo");
            return (Criteria) this;
        }

        public Criteria andPrincipalContactInfoNotIn(List<String> values) {
            addCriterion("principal_contact_info not in", values, "principalContactInfo");
            return (Criteria) this;
        }

        public Criteria andPrincipalContactInfoBetween(String value1, String value2) {
            addCriterion("principal_contact_info between", value1, value2, "principalContactInfo");
            return (Criteria) this;
        }

        public Criteria andPrincipalContactInfoNotBetween(String value1, String value2) {
            addCriterion("principal_contact_info not between", value1, value2, "principalContactInfo");
            return (Criteria) this;
        }

        public Criteria andLeaderIsNull() {
            addCriterion("leader is null");
            return (Criteria) this;
        }

        public Criteria andLeaderIsNotNull() {
            addCriterion("leader is not null");
            return (Criteria) this;
        }

        public Criteria andLeaderEqualTo(String value) {
            addCriterion("leader =", value, "leader");
            return (Criteria) this;
        }

        public Criteria andLeaderNotEqualTo(String value) {
            addCriterion("leader <>", value, "leader");
            return (Criteria) this;
        }

        public Criteria andLeaderGreaterThan(String value) {
            addCriterion("leader >", value, "leader");
            return (Criteria) this;
        }

        public Criteria andLeaderGreaterThanOrEqualTo(String value) {
            addCriterion("leader >=", value, "leader");
            return (Criteria) this;
        }

        public Criteria andLeaderLessThan(String value) {
            addCriterion("leader <", value, "leader");
            return (Criteria) this;
        }

        public Criteria andLeaderLessThanOrEqualTo(String value) {
            addCriterion("leader <=", value, "leader");
            return (Criteria) this;
        }

        public Criteria andLeaderLike(String value) {
            addCriterion("leader like", value, "leader");
            return (Criteria) this;
        }

        public Criteria andLeaderNotLike(String value) {
            addCriterion("leader not like", value, "leader");
            return (Criteria) this;
        }

        public Criteria andLeaderIn(List<String> values) {
            addCriterion("leader in", values, "leader");
            return (Criteria) this;
        }

        public Criteria andLeaderNotIn(List<String> values) {
            addCriterion("leader not in", values, "leader");
            return (Criteria) this;
        }

        public Criteria andLeaderBetween(String value1, String value2) {
            addCriterion("leader between", value1, value2, "leader");
            return (Criteria) this;
        }

        public Criteria andLeaderNotBetween(String value1, String value2) {
            addCriterion("leader not between", value1, value2, "leader");
            return (Criteria) this;
        }

        public Criteria andLeaderContactInfoIsNull() {
            addCriterion("leader_contact_info is null");
            return (Criteria) this;
        }

        public Criteria andLeaderContactInfoIsNotNull() {
            addCriterion("leader_contact_info is not null");
            return (Criteria) this;
        }

        public Criteria andLeaderContactInfoEqualTo(String value) {
            addCriterion("leader_contact_info =", value, "leaderContactInfo");
            return (Criteria) this;
        }

        public Criteria andLeaderContactInfoNotEqualTo(String value) {
            addCriterion("leader_contact_info <>", value, "leaderContactInfo");
            return (Criteria) this;
        }

        public Criteria andLeaderContactInfoGreaterThan(String value) {
            addCriterion("leader_contact_info >", value, "leaderContactInfo");
            return (Criteria) this;
        }

        public Criteria andLeaderContactInfoGreaterThanOrEqualTo(String value) {
            addCriterion("leader_contact_info >=", value, "leaderContactInfo");
            return (Criteria) this;
        }

        public Criteria andLeaderContactInfoLessThan(String value) {
            addCriterion("leader_contact_info <", value, "leaderContactInfo");
            return (Criteria) this;
        }

        public Criteria andLeaderContactInfoLessThanOrEqualTo(String value) {
            addCriterion("leader_contact_info <=", value, "leaderContactInfo");
            return (Criteria) this;
        }

        public Criteria andLeaderContactInfoLike(String value) {
            addCriterion("leader_contact_info like", value, "leaderContactInfo");
            return (Criteria) this;
        }

        public Criteria andLeaderContactInfoNotLike(String value) {
            addCriterion("leader_contact_info not like", value, "leaderContactInfo");
            return (Criteria) this;
        }

        public Criteria andLeaderContactInfoIn(List<String> values) {
            addCriterion("leader_contact_info in", values, "leaderContactInfo");
            return (Criteria) this;
        }

        public Criteria andLeaderContactInfoNotIn(List<String> values) {
            addCriterion("leader_contact_info not in", values, "leaderContactInfo");
            return (Criteria) this;
        }

        public Criteria andLeaderContactInfoBetween(String value1, String value2) {
            addCriterion("leader_contact_info between", value1, value2, "leaderContactInfo");
            return (Criteria) this;
        }

        public Criteria andLeaderContactInfoNotBetween(String value1, String value2) {
            addCriterion("leader_contact_info not between", value1, value2, "leaderContactInfo");
            return (Criteria) this;
        }

        public Criteria andSecureLeaderIsNull() {
            addCriterion("secure_leader is null");
            return (Criteria) this;
        }

        public Criteria andSecureLeaderIsNotNull() {
            addCriterion("secure_leader is not null");
            return (Criteria) this;
        }

        public Criteria andSecureLeaderEqualTo(String value) {
            addCriterion("secure_leader =", value, "secureLeader");
            return (Criteria) this;
        }

        public Criteria andSecureLeaderNotEqualTo(String value) {
            addCriterion("secure_leader <>", value, "secureLeader");
            return (Criteria) this;
        }

        public Criteria andSecureLeaderGreaterThan(String value) {
            addCriterion("secure_leader >", value, "secureLeader");
            return (Criteria) this;
        }

        public Criteria andSecureLeaderGreaterThanOrEqualTo(String value) {
            addCriterion("secure_leader >=", value, "secureLeader");
            return (Criteria) this;
        }

        public Criteria andSecureLeaderLessThan(String value) {
            addCriterion("secure_leader <", value, "secureLeader");
            return (Criteria) this;
        }

        public Criteria andSecureLeaderLessThanOrEqualTo(String value) {
            addCriterion("secure_leader <=", value, "secureLeader");
            return (Criteria) this;
        }

        public Criteria andSecureLeaderLike(String value) {
            addCriterion("secure_leader like", value, "secureLeader");
            return (Criteria) this;
        }

        public Criteria andSecureLeaderNotLike(String value) {
            addCriterion("secure_leader not like", value, "secureLeader");
            return (Criteria) this;
        }

        public Criteria andSecureLeaderIn(List<String> values) {
            addCriterion("secure_leader in", values, "secureLeader");
            return (Criteria) this;
        }

        public Criteria andSecureLeaderNotIn(List<String> values) {
            addCriterion("secure_leader not in", values, "secureLeader");
            return (Criteria) this;
        }

        public Criteria andSecureLeaderBetween(String value1, String value2) {
            addCriterion("secure_leader between", value1, value2, "secureLeader");
            return (Criteria) this;
        }

        public Criteria andSecureLeaderNotBetween(String value1, String value2) {
            addCriterion("secure_leader not between", value1, value2, "secureLeader");
            return (Criteria) this;
        }

        public Criteria andSecureLeaderContactInfoIsNull() {
            addCriterion("secure_leader_contact_info is null");
            return (Criteria) this;
        }

        public Criteria andSecureLeaderContactInfoIsNotNull() {
            addCriterion("secure_leader_contact_info is not null");
            return (Criteria) this;
        }

        public Criteria andSecureLeaderContactInfoEqualTo(String value) {
            addCriterion("secure_leader_contact_info =", value, "secureLeaderContactInfo");
            return (Criteria) this;
        }

        public Criteria andSecureLeaderContactInfoNotEqualTo(String value) {
            addCriterion("secure_leader_contact_info <>", value, "secureLeaderContactInfo");
            return (Criteria) this;
        }

        public Criteria andSecureLeaderContactInfoGreaterThan(String value) {
            addCriterion("secure_leader_contact_info >", value, "secureLeaderContactInfo");
            return (Criteria) this;
        }

        public Criteria andSecureLeaderContactInfoGreaterThanOrEqualTo(String value) {
            addCriterion("secure_leader_contact_info >=", value, "secureLeaderContactInfo");
            return (Criteria) this;
        }

        public Criteria andSecureLeaderContactInfoLessThan(String value) {
            addCriterion("secure_leader_contact_info <", value, "secureLeaderContactInfo");
            return (Criteria) this;
        }

        public Criteria andSecureLeaderContactInfoLessThanOrEqualTo(String value) {
            addCriterion("secure_leader_contact_info <=", value, "secureLeaderContactInfo");
            return (Criteria) this;
        }

        public Criteria andSecureLeaderContactInfoLike(String value) {
            addCriterion("secure_leader_contact_info like", value, "secureLeaderContactInfo");
            return (Criteria) this;
        }

        public Criteria andSecureLeaderContactInfoNotLike(String value) {
            addCriterion("secure_leader_contact_info not like", value, "secureLeaderContactInfo");
            return (Criteria) this;
        }

        public Criteria andSecureLeaderContactInfoIn(List<String> values) {
            addCriterion("secure_leader_contact_info in", values, "secureLeaderContactInfo");
            return (Criteria) this;
        }

        public Criteria andSecureLeaderContactInfoNotIn(List<String> values) {
            addCriterion("secure_leader_contact_info not in", values, "secureLeaderContactInfo");
            return (Criteria) this;
        }

        public Criteria andSecureLeaderContactInfoBetween(String value1, String value2) {
            addCriterion("secure_leader_contact_info between", value1, value2, "secureLeaderContactInfo");
            return (Criteria) this;
        }

        public Criteria andSecureLeaderContactInfoNotBetween(String value1, String value2) {
            addCriterion("secure_leader_contact_info not between", value1, value2, "secureLeaderContactInfo");
            return (Criteria) this;
        }

        public Criteria andSecureCodeIsNull() {
            addCriterion("secure_code is null");
            return (Criteria) this;
        }

        public Criteria andSecureCodeIsNotNull() {
            addCriterion("secure_code is not null");
            return (Criteria) this;
        }

        public Criteria andSecureCodeEqualTo(String value) {
            addCriterion("secure_code =", value, "secureCode");
            return (Criteria) this;
        }

        public Criteria andSecureCodeNotEqualTo(String value) {
            addCriterion("secure_code <>", value, "secureCode");
            return (Criteria) this;
        }

        public Criteria andSecureCodeGreaterThan(String value) {
            addCriterion("secure_code >", value, "secureCode");
            return (Criteria) this;
        }

        public Criteria andSecureCodeGreaterThanOrEqualTo(String value) {
            addCriterion("secure_code >=", value, "secureCode");
            return (Criteria) this;
        }

        public Criteria andSecureCodeLessThan(String value) {
            addCriterion("secure_code <", value, "secureCode");
            return (Criteria) this;
        }

        public Criteria andSecureCodeLessThanOrEqualTo(String value) {
            addCriterion("secure_code <=", value, "secureCode");
            return (Criteria) this;
        }

        public Criteria andSecureCodeLike(String value) {
            addCriterion("secure_code like", value, "secureCode");
            return (Criteria) this;
        }

        public Criteria andSecureCodeNotLike(String value) {
            addCriterion("secure_code not like", value, "secureCode");
            return (Criteria) this;
        }

        public Criteria andSecureCodeIn(List<String> values) {
            addCriterion("secure_code in", values, "secureCode");
            return (Criteria) this;
        }

        public Criteria andSecureCodeNotIn(List<String> values) {
            addCriterion("secure_code not in", values, "secureCode");
            return (Criteria) this;
        }

        public Criteria andSecureCodeBetween(String value1, String value2) {
            addCriterion("secure_code between", value1, value2, "secureCode");
            return (Criteria) this;
        }

        public Criteria andSecureCodeNotBetween(String value1, String value2) {
            addCriterion("secure_code not between", value1, value2, "secureCode");
            return (Criteria) this;
        }

        public Criteria andSecureBegintimeIsNull() {
            addCriterion("secure_begintime is null");
            return (Criteria) this;
        }

        public Criteria andSecureBegintimeIsNotNull() {
            addCriterion("secure_begintime is not null");
            return (Criteria) this;
        }

        public Criteria andSecureBegintimeEqualTo(Date value) {
            addCriterionForJDBCDate("secure_begintime =", value, "secureBegintime");
            return (Criteria) this;
        }

        public Criteria andSecureBegintimeNotEqualTo(Date value) {
            addCriterionForJDBCDate("secure_begintime <>", value, "secureBegintime");
            return (Criteria) this;
        }

        public Criteria andSecureBegintimeGreaterThan(Date value) {
            addCriterionForJDBCDate("secure_begintime >", value, "secureBegintime");
            return (Criteria) this;
        }

        public Criteria andSecureBegintimeGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("secure_begintime >=", value, "secureBegintime");
            return (Criteria) this;
        }

        public Criteria andSecureBegintimeLessThan(Date value) {
            addCriterionForJDBCDate("secure_begintime <", value, "secureBegintime");
            return (Criteria) this;
        }

        public Criteria andSecureBegintimeLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("secure_begintime <=", value, "secureBegintime");
            return (Criteria) this;
        }

        public Criteria andSecureBegintimeIn(List<Date> values) {
            addCriterionForJDBCDate("secure_begintime in", values, "secureBegintime");
            return (Criteria) this;
        }

        public Criteria andSecureBegintimeNotIn(List<Date> values) {
            addCriterionForJDBCDate("secure_begintime not in", values, "secureBegintime");
            return (Criteria) this;
        }

        public Criteria andSecureBegintimeBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("secure_begintime between", value1, value2, "secureBegintime");
            return (Criteria) this;
        }

        public Criteria andSecureBegintimeNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("secure_begintime not between", value1, value2, "secureBegintime");
            return (Criteria) this;
        }

        public Criteria andSecureEndtimeIsNull() {
            addCriterion("secure_endtime is null");
            return (Criteria) this;
        }

        public Criteria andSecureEndtimeIsNotNull() {
            addCriterion("secure_endtime is not null");
            return (Criteria) this;
        }

        public Criteria andSecureEndtimeEqualTo(Date value) {
            addCriterionForJDBCDate("secure_endtime =", value, "secureEndtime");
            return (Criteria) this;
        }

        public Criteria andSecureEndtimeNotEqualTo(Date value) {
            addCriterionForJDBCDate("secure_endtime <>", value, "secureEndtime");
            return (Criteria) this;
        }

        public Criteria andSecureEndtimeGreaterThan(Date value) {
            addCriterionForJDBCDate("secure_endtime >", value, "secureEndtime");
            return (Criteria) this;
        }

        public Criteria andSecureEndtimeGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("secure_endtime >=", value, "secureEndtime");
            return (Criteria) this;
        }

        public Criteria andSecureEndtimeLessThan(Date value) {
            addCriterionForJDBCDate("secure_endtime <", value, "secureEndtime");
            return (Criteria) this;
        }

        public Criteria andSecureEndtimeLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("secure_endtime <=", value, "secureEndtime");
            return (Criteria) this;
        }

        public Criteria andSecureEndtimeIn(List<Date> values) {
            addCriterionForJDBCDate("secure_endtime in", values, "secureEndtime");
            return (Criteria) this;
        }

        public Criteria andSecureEndtimeNotIn(List<Date> values) {
            addCriterionForJDBCDate("secure_endtime not in", values, "secureEndtime");
            return (Criteria) this;
        }

        public Criteria andSecureEndtimeBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("secure_endtime between", value1, value2, "secureEndtime");
            return (Criteria) this;
        }

        public Criteria andSecureEndtimeNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("secure_endtime not between", value1, value2, "secureEndtime");
            return (Criteria) this;
        }

        public Criteria andRemarksIsNull() {
            addCriterion("remarks is null");
            return (Criteria) this;
        }

        public Criteria andRemarksIsNotNull() {
            addCriterion("remarks is not null");
            return (Criteria) this;
        }

        public Criteria andRemarksEqualTo(String value) {
            addCriterion("remarks =", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksNotEqualTo(String value) {
            addCriterion("remarks <>", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksGreaterThan(String value) {
            addCriterion("remarks >", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksGreaterThanOrEqualTo(String value) {
            addCriterion("remarks >=", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksLessThan(String value) {
            addCriterion("remarks <", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksLessThanOrEqualTo(String value) {
            addCriterion("remarks <=", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksLike(String value) {
            addCriterion("remarks like", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksNotLike(String value) {
            addCriterion("remarks not like", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksIn(List<String> values) {
            addCriterion("remarks in", values, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksNotIn(List<String> values) {
            addCriterion("remarks not in", values, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksBetween(String value1, String value2) {
            addCriterion("remarks between", value1, value2, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksNotBetween(String value1, String value2) {
            addCriterion("remarks not between", value1, value2, "remarks");
            return (Criteria) this;
        }

        public Criteria andGmtCreateIsNull() {
            addCriterion("gmt_create is null");
            return (Criteria) this;
        }

        public Criteria andGmtCreateIsNotNull() {
            addCriterion("gmt_create is not null");
            return (Criteria) this;
        }

        public Criteria andGmtCreateEqualTo(Long value) {
            addCriterion("gmt_create =", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateNotEqualTo(Long value) {
            addCriterion("gmt_create <>", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateGreaterThan(Long value) {
            addCriterion("gmt_create >", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateGreaterThanOrEqualTo(Long value) {
            addCriterion("gmt_create >=", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateLessThan(Long value) {
            addCriterion("gmt_create <", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateLessThanOrEqualTo(Long value) {
            addCriterion("gmt_create <=", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateIn(List<Long> values) {
            addCriterion("gmt_create in", values, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateNotIn(List<Long> values) {
            addCriterion("gmt_create not in", values, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateBetween(Long value1, Long value2) {
            addCriterion("gmt_create between", value1, value2, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateNotBetween(Long value1, Long value2) {
            addCriterion("gmt_create not between", value1, value2, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtModifyIsNull() {
            addCriterion("gmt_modify is null");
            return (Criteria) this;
        }

        public Criteria andGmtModifyIsNotNull() {
            addCriterion("gmt_modify is not null");
            return (Criteria) this;
        }

        public Criteria andGmtModifyEqualTo(Long value) {
            addCriterion("gmt_modify =", value, "gmtModify");
            return (Criteria) this;
        }

        public Criteria andGmtModifyNotEqualTo(Long value) {
            addCriterion("gmt_modify <>", value, "gmtModify");
            return (Criteria) this;
        }

        public Criteria andGmtModifyGreaterThan(Long value) {
            addCriterion("gmt_modify >", value, "gmtModify");
            return (Criteria) this;
        }

        public Criteria andGmtModifyGreaterThanOrEqualTo(Long value) {
            addCriterion("gmt_modify >=", value, "gmtModify");
            return (Criteria) this;
        }

        public Criteria andGmtModifyLessThan(Long value) {
            addCriterion("gmt_modify <", value, "gmtModify");
            return (Criteria) this;
        }

        public Criteria andGmtModifyLessThanOrEqualTo(Long value) {
            addCriterion("gmt_modify <=", value, "gmtModify");
            return (Criteria) this;
        }

        public Criteria andGmtModifyIn(List<Long> values) {
            addCriterion("gmt_modify in", values, "gmtModify");
            return (Criteria) this;
        }

        public Criteria andGmtModifyNotIn(List<Long> values) {
            addCriterion("gmt_modify not in", values, "gmtModify");
            return (Criteria) this;
        }

        public Criteria andGmtModifyBetween(Long value1, Long value2) {
            addCriterion("gmt_modify between", value1, value2, "gmtModify");
            return (Criteria) this;
        }

        public Criteria andGmtModifyNotBetween(Long value1, Long value2) {
            addCriterion("gmt_modify not between", value1, value2, "gmtModify");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table servers_info
     *
     * @mbg.generated do_not_delete_during_merge Tue Apr 14 13:57:25 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table servers_info
     *
     * @mbg.generated Tue Apr 14 13:57:25 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}