package com.cloud.platform.model;

public class ServerInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column servers_info.id
     *
     * @mbg.generated Sun Apr 26 13:17:26 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column servers_info.identifer
     *
     * @mbg.generated Sun Apr 26 13:17:26 CST 2020
     */
    private String identifer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column servers_info.server_name
     *
     * @mbg.generated Sun Apr 26 13:17:26 CST 2020
     */
    private String serverName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column servers_info.abbreviation
     *
     * @mbg.generated Sun Apr 26 13:17:26 CST 2020
     */
    private String abbreviation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column servers_info.type
     *
     * @mbg.generated Sun Apr 26 13:17:26 CST 2020
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column servers_info.credit_code
     *
     * @mbg.generated Sun Apr 26 13:17:26 CST 2020
     */
    private Integer creditCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column servers_info.location
     *
     * @mbg.generated Sun Apr 26 13:17:26 CST 2020
     */
    private String location;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column servers_info.present
     *
     * @mbg.generated Sun Apr 26 13:17:26 CST 2020
     */
    private String present;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column servers_info.registered_capital
     *
     * @mbg.generated Sun Apr 26 13:17:26 CST 2020
     */
    private Integer registeredCapital;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column servers_info.create_time
     *
     * @mbg.generated Sun Apr 26 13:17:26 CST 2020
     */
    private String createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column servers_info.manage_range
     *
     * @mbg.generated Sun Apr 26 13:17:26 CST 2020
     */
    private String manageRange;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column servers_info.manage_begintime
     *
     * @mbg.generated Sun Apr 26 13:17:26 CST 2020
     */
    private String manageBegintime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column servers_info.manage_endtime
     *
     * @mbg.generated Sun Apr 26 13:17:26 CST 2020
     */
    private String manageEndtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column servers_info.registrar
     *
     * @mbg.generated Sun Apr 26 13:17:26 CST 2020
     */
    private String registrar;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column servers_info.issue_time
     *
     * @mbg.generated Sun Apr 26 13:17:26 CST 2020
     */
    private String issueTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column servers_info.principal
     *
     * @mbg.generated Sun Apr 26 13:17:26 CST 2020
     */
    private String principal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column servers_info.principal_contact_info
     *
     * @mbg.generated Sun Apr 26 13:17:26 CST 2020
     */
    private String principalContactInfo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column servers_info.leader
     *
     * @mbg.generated Sun Apr 26 13:17:26 CST 2020
     */
    private String leader;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column servers_info.leader_contact_info
     *
     * @mbg.generated Sun Apr 26 13:17:26 CST 2020
     */
    private String leaderContactInfo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column servers_info.secure_leader
     *
     * @mbg.generated Sun Apr 26 13:17:26 CST 2020
     */
    private String secureLeader;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column servers_info.secure_leader_contact_info
     *
     * @mbg.generated Sun Apr 26 13:17:26 CST 2020
     */
    private String secureLeaderContactInfo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column servers_info.secure_code
     *
     * @mbg.generated Sun Apr 26 13:17:26 CST 2020
     */
    private String secureCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column servers_info.secure_begintime
     *
     * @mbg.generated Sun Apr 26 13:17:26 CST 2020
     */
    private String secureBegintime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column servers_info.secure_endtime
     *
     * @mbg.generated Sun Apr 26 13:17:26 CST 2020
     */
    private String secureEndtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column servers_info.remarks
     *
     * @mbg.generated Sun Apr 26 13:17:26 CST 2020
     */
    private String remarks;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column servers_info.gmt_create
     *
     * @mbg.generated Sun Apr 26 13:17:26 CST 2020
     */
    private Long gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column servers_info.gmt_modify
     *
     * @mbg.generated Sun Apr 26 13:17:26 CST 2020
     */
    private Long gmtModify;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column servers_info.id
     *
     * @return the value of servers_info.id
     *
     * @mbg.generated Sun Apr 26 13:17:26 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column servers_info.id
     *
     * @param id the value for servers_info.id
     *
     * @mbg.generated Sun Apr 26 13:17:26 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column servers_info.identifer
     *
     * @return the value of servers_info.identifer
     *
     * @mbg.generated Sun Apr 26 13:17:26 CST 2020
     */
    public String getIdentifer() {
        return identifer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column servers_info.identifer
     *
     * @param identifer the value for servers_info.identifer
     *
     * @mbg.generated Sun Apr 26 13:17:26 CST 2020
     */
    public void setIdentifer(String identifer) {
        this.identifer = identifer == null ? null : identifer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column servers_info.server_name
     *
     * @return the value of servers_info.server_name
     *
     * @mbg.generated Sun Apr 26 13:17:26 CST 2020
     */
    public String getServerName() {
        return serverName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column servers_info.server_name
     *
     * @param serverName the value for servers_info.server_name
     *
     * @mbg.generated Sun Apr 26 13:17:26 CST 2020
     */
    public void setServerName(String serverName) {
        this.serverName = serverName == null ? null : serverName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column servers_info.abbreviation
     *
     * @return the value of servers_info.abbreviation
     *
     * @mbg.generated Sun Apr 26 13:17:26 CST 2020
     */
    public String getAbbreviation() {
        return abbreviation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column servers_info.abbreviation
     *
     * @param abbreviation the value for servers_info.abbreviation
     *
     * @mbg.generated Sun Apr 26 13:17:26 CST 2020
     */
    public void setAbbreviation(String abbreviation) {
        this.abbreviation = abbreviation == null ? null : abbreviation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column servers_info.type
     *
     * @return the value of servers_info.type
     *
     * @mbg.generated Sun Apr 26 13:17:26 CST 2020
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column servers_info.type
     *
     * @param type the value for servers_info.type
     *
     * @mbg.generated Sun Apr 26 13:17:26 CST 2020
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column servers_info.credit_code
     *
     * @return the value of servers_info.credit_code
     *
     * @mbg.generated Sun Apr 26 13:17:26 CST 2020
     */
    public Integer getCreditCode() {
        return creditCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column servers_info.credit_code
     *
     * @param creditCode the value for servers_info.credit_code
     *
     * @mbg.generated Sun Apr 26 13:17:26 CST 2020
     */
    public void setCreditCode(Integer creditCode) {
        this.creditCode = creditCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column servers_info.location
     *
     * @return the value of servers_info.location
     *
     * @mbg.generated Sun Apr 26 13:17:26 CST 2020
     */
    public String getLocation() {
        return location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column servers_info.location
     *
     * @param location the value for servers_info.location
     *
     * @mbg.generated Sun Apr 26 13:17:26 CST 2020
     */
    public void setLocation(String location) {
        this.location = location == null ? null : location.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column servers_info.present
     *
     * @return the value of servers_info.present
     *
     * @mbg.generated Sun Apr 26 13:17:26 CST 2020
     */
    public String getPresent() {
        return present;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column servers_info.present
     *
     * @param present the value for servers_info.present
     *
     * @mbg.generated Sun Apr 26 13:17:26 CST 2020
     */
    public void setPresent(String present) {
        this.present = present == null ? null : present.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column servers_info.registered_capital
     *
     * @return the value of servers_info.registered_capital
     *
     * @mbg.generated Sun Apr 26 13:17:26 CST 2020
     */
    public Integer getRegisteredCapital() {
        return registeredCapital;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column servers_info.registered_capital
     *
     * @param registeredCapital the value for servers_info.registered_capital
     *
     * @mbg.generated Sun Apr 26 13:17:26 CST 2020
     */
    public void setRegisteredCapital(Integer registeredCapital) {
        this.registeredCapital = registeredCapital;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column servers_info.create_time
     *
     * @return the value of servers_info.create_time
     *
     * @mbg.generated Sun Apr 26 13:17:26 CST 2020
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column servers_info.create_time
     *
     * @param createTime the value for servers_info.create_time
     *
     * @mbg.generated Sun Apr 26 13:17:26 CST 2020
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column servers_info.manage_range
     *
     * @return the value of servers_info.manage_range
     *
     * @mbg.generated Sun Apr 26 13:17:26 CST 2020
     */
    public String getManageRange() {
        return manageRange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column servers_info.manage_range
     *
     * @param manageRange the value for servers_info.manage_range
     *
     * @mbg.generated Sun Apr 26 13:17:26 CST 2020
     */
    public void setManageRange(String manageRange) {
        this.manageRange = manageRange == null ? null : manageRange.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column servers_info.manage_begintime
     *
     * @return the value of servers_info.manage_begintime
     *
     * @mbg.generated Sun Apr 26 13:17:26 CST 2020
     */
    public String getManageBegintime() {
        return manageBegintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column servers_info.manage_begintime
     *
     * @param manageBegintime the value for servers_info.manage_begintime
     *
     * @mbg.generated Sun Apr 26 13:17:26 CST 2020
     */
    public void setManageBegintime(String manageBegintime) {
        this.manageBegintime = manageBegintime == null ? null : manageBegintime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column servers_info.manage_endtime
     *
     * @return the value of servers_info.manage_endtime
     *
     * @mbg.generated Sun Apr 26 13:17:26 CST 2020
     */
    public String getManageEndtime() {
        return manageEndtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column servers_info.manage_endtime
     *
     * @param manageEndtime the value for servers_info.manage_endtime
     *
     * @mbg.generated Sun Apr 26 13:17:26 CST 2020
     */
    public void setManageEndtime(String manageEndtime) {
        this.manageEndtime = manageEndtime == null ? null : manageEndtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column servers_info.registrar
     *
     * @return the value of servers_info.registrar
     *
     * @mbg.generated Sun Apr 26 13:17:26 CST 2020
     */
    public String getRegistrar() {
        return registrar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column servers_info.registrar
     *
     * @param registrar the value for servers_info.registrar
     *
     * @mbg.generated Sun Apr 26 13:17:26 CST 2020
     */
    public void setRegistrar(String registrar) {
        this.registrar = registrar == null ? null : registrar.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column servers_info.issue_time
     *
     * @return the value of servers_info.issue_time
     *
     * @mbg.generated Sun Apr 26 13:17:26 CST 2020
     */
    public String getIssueTime() {
        return issueTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column servers_info.issue_time
     *
     * @param issueTime the value for servers_info.issue_time
     *
     * @mbg.generated Sun Apr 26 13:17:26 CST 2020
     */
    public void setIssueTime(String issueTime) {
        this.issueTime = issueTime == null ? null : issueTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column servers_info.principal
     *
     * @return the value of servers_info.principal
     *
     * @mbg.generated Sun Apr 26 13:17:26 CST 2020
     */
    public String getPrincipal() {
        return principal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column servers_info.principal
     *
     * @param principal the value for servers_info.principal
     *
     * @mbg.generated Sun Apr 26 13:17:26 CST 2020
     */
    public void setPrincipal(String principal) {
        this.principal = principal == null ? null : principal.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column servers_info.principal_contact_info
     *
     * @return the value of servers_info.principal_contact_info
     *
     * @mbg.generated Sun Apr 26 13:17:26 CST 2020
     */
    public String getPrincipalContactInfo() {
        return principalContactInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column servers_info.principal_contact_info
     *
     * @param principalContactInfo the value for servers_info.principal_contact_info
     *
     * @mbg.generated Sun Apr 26 13:17:26 CST 2020
     */
    public void setPrincipalContactInfo(String principalContactInfo) {
        this.principalContactInfo = principalContactInfo == null ? null : principalContactInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column servers_info.leader
     *
     * @return the value of servers_info.leader
     *
     * @mbg.generated Sun Apr 26 13:17:26 CST 2020
     */
    public String getLeader() {
        return leader;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column servers_info.leader
     *
     * @param leader the value for servers_info.leader
     *
     * @mbg.generated Sun Apr 26 13:17:26 CST 2020
     */
    public void setLeader(String leader) {
        this.leader = leader == null ? null : leader.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column servers_info.leader_contact_info
     *
     * @return the value of servers_info.leader_contact_info
     *
     * @mbg.generated Sun Apr 26 13:17:26 CST 2020
     */
    public String getLeaderContactInfo() {
        return leaderContactInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column servers_info.leader_contact_info
     *
     * @param leaderContactInfo the value for servers_info.leader_contact_info
     *
     * @mbg.generated Sun Apr 26 13:17:26 CST 2020
     */
    public void setLeaderContactInfo(String leaderContactInfo) {
        this.leaderContactInfo = leaderContactInfo == null ? null : leaderContactInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column servers_info.secure_leader
     *
     * @return the value of servers_info.secure_leader
     *
     * @mbg.generated Sun Apr 26 13:17:26 CST 2020
     */
    public String getSecureLeader() {
        return secureLeader;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column servers_info.secure_leader
     *
     * @param secureLeader the value for servers_info.secure_leader
     *
     * @mbg.generated Sun Apr 26 13:17:26 CST 2020
     */
    public void setSecureLeader(String secureLeader) {
        this.secureLeader = secureLeader == null ? null : secureLeader.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column servers_info.secure_leader_contact_info
     *
     * @return the value of servers_info.secure_leader_contact_info
     *
     * @mbg.generated Sun Apr 26 13:17:26 CST 2020
     */
    public String getSecureLeaderContactInfo() {
        return secureLeaderContactInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column servers_info.secure_leader_contact_info
     *
     * @param secureLeaderContactInfo the value for servers_info.secure_leader_contact_info
     *
     * @mbg.generated Sun Apr 26 13:17:26 CST 2020
     */
    public void setSecureLeaderContactInfo(String secureLeaderContactInfo) {
        this.secureLeaderContactInfo = secureLeaderContactInfo == null ? null : secureLeaderContactInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column servers_info.secure_code
     *
     * @return the value of servers_info.secure_code
     *
     * @mbg.generated Sun Apr 26 13:17:26 CST 2020
     */
    public String getSecureCode() {
        return secureCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column servers_info.secure_code
     *
     * @param secureCode the value for servers_info.secure_code
     *
     * @mbg.generated Sun Apr 26 13:17:26 CST 2020
     */
    public void setSecureCode(String secureCode) {
        this.secureCode = secureCode == null ? null : secureCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column servers_info.secure_begintime
     *
     * @return the value of servers_info.secure_begintime
     *
     * @mbg.generated Sun Apr 26 13:17:26 CST 2020
     */
    public String getSecureBegintime() {
        return secureBegintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column servers_info.secure_begintime
     *
     * @param secureBegintime the value for servers_info.secure_begintime
     *
     * @mbg.generated Sun Apr 26 13:17:26 CST 2020
     */
    public void setSecureBegintime(String secureBegintime) {
        this.secureBegintime = secureBegintime == null ? null : secureBegintime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column servers_info.secure_endtime
     *
     * @return the value of servers_info.secure_endtime
     *
     * @mbg.generated Sun Apr 26 13:17:26 CST 2020
     */
    public String getSecureEndtime() {
        return secureEndtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column servers_info.secure_endtime
     *
     * @param secureEndtime the value for servers_info.secure_endtime
     *
     * @mbg.generated Sun Apr 26 13:17:26 CST 2020
     */
    public void setSecureEndtime(String secureEndtime) {
        this.secureEndtime = secureEndtime == null ? null : secureEndtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column servers_info.remarks
     *
     * @return the value of servers_info.remarks
     *
     * @mbg.generated Sun Apr 26 13:17:26 CST 2020
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column servers_info.remarks
     *
     * @param remarks the value for servers_info.remarks
     *
     * @mbg.generated Sun Apr 26 13:17:26 CST 2020
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column servers_info.gmt_create
     *
     * @return the value of servers_info.gmt_create
     *
     * @mbg.generated Sun Apr 26 13:17:26 CST 2020
     */
    public Long getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column servers_info.gmt_create
     *
     * @param gmtCreate the value for servers_info.gmt_create
     *
     * @mbg.generated Sun Apr 26 13:17:26 CST 2020
     */
    public void setGmtCreate(Long gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column servers_info.gmt_modify
     *
     * @return the value of servers_info.gmt_modify
     *
     * @mbg.generated Sun Apr 26 13:17:26 CST 2020
     */
    public Long getGmtModify() {
        return gmtModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column servers_info.gmt_modify
     *
     * @param gmtModify the value for servers_info.gmt_modify
     *
     * @mbg.generated Sun Apr 26 13:17:26 CST 2020
     */
    public void setGmtModify(Long gmtModify) {
        this.gmtModify = gmtModify;
    }
}