package com.cloud.platform.model;

public class UnAssetDevice {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column un_asset_device.id
     *
     * @mbg.generated Mon Apr 27 21:47:54 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column un_asset_device.affiliation
     *
     * @mbg.generated Mon Apr 27 21:47:54 CST 2020
     */
    private String affiliation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column un_asset_device.un_asset_type
     *
     * @mbg.generated Mon Apr 27 21:47:54 CST 2020
     */
    private String unAssetType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column un_asset_device.count
     *
     * @mbg.generated Mon Apr 27 21:47:54 CST 2020
     */
    private Integer count;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column un_asset_device.unit
     *
     * @mbg.generated Mon Apr 27 21:47:54 CST 2020
     */
    private String unit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column un_asset_device.specification
     *
     * @mbg.generated Mon Apr 27 21:47:54 CST 2020
     */
    private String specification;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column un_asset_device.id
     *
     * @return the value of un_asset_device.id
     *
     * @mbg.generated Mon Apr 27 21:47:54 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column un_asset_device.id
     *
     * @param id the value for un_asset_device.id
     *
     * @mbg.generated Mon Apr 27 21:47:54 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column un_asset_device.affiliation
     *
     * @return the value of un_asset_device.affiliation
     *
     * @mbg.generated Mon Apr 27 21:47:54 CST 2020
     */
    public String getAffiliation() {
        return affiliation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column un_asset_device.affiliation
     *
     * @param affiliation the value for un_asset_device.affiliation
     *
     * @mbg.generated Mon Apr 27 21:47:54 CST 2020
     */
    public void setAffiliation(String affiliation) {
        this.affiliation = affiliation == null ? null : affiliation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column un_asset_device.un_asset_type
     *
     * @return the value of un_asset_device.un_asset_type
     *
     * @mbg.generated Mon Apr 27 21:47:54 CST 2020
     */
    public String getUnAssetType() {
        return unAssetType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column un_asset_device.un_asset_type
     *
     * @param unAssetType the value for un_asset_device.un_asset_type
     *
     * @mbg.generated Mon Apr 27 21:47:54 CST 2020
     */
    public void setUnAssetType(String unAssetType) {
        this.unAssetType = unAssetType == null ? null : unAssetType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column un_asset_device.count
     *
     * @return the value of un_asset_device.count
     *
     * @mbg.generated Mon Apr 27 21:47:54 CST 2020
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column un_asset_device.count
     *
     * @param count the value for un_asset_device.count
     *
     * @mbg.generated Mon Apr 27 21:47:54 CST 2020
     */
    public void setCount(Integer count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column un_asset_device.unit
     *
     * @return the value of un_asset_device.unit
     *
     * @mbg.generated Mon Apr 27 21:47:54 CST 2020
     */
    public String getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column un_asset_device.unit
     *
     * @param unit the value for un_asset_device.unit
     *
     * @mbg.generated Mon Apr 27 21:47:54 CST 2020
     */
    public void setUnit(String unit) {
        this.unit = unit == null ? null : unit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column un_asset_device.specification
     *
     * @return the value of un_asset_device.specification
     *
     * @mbg.generated Mon Apr 27 21:47:54 CST 2020
     */
    public String getSpecification() {
        return specification;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column un_asset_device.specification
     *
     * @param specification the value for un_asset_device.specification
     *
     * @mbg.generated Mon Apr 27 21:47:54 CST 2020
     */
    public void setSpecification(String specification) {
        this.specification = specification == null ? null : specification.trim();
    }
}