package com.cloud.platform.model;

import java.util.ArrayList;
import java.util.List;

public class UnAssetTypeExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table un_asset_type
     *
     * @mbg.generated Sun Apr 26 13:17:26 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table un_asset_type
     *
     * @mbg.generated Sun Apr 26 13:17:26 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table un_asset_type
     *
     * @mbg.generated Sun Apr 26 13:17:26 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table un_asset_type
     *
     * @mbg.generated Sun Apr 26 13:17:26 CST 2020
     */
    public UnAssetTypeExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table un_asset_type
     *
     * @mbg.generated Sun Apr 26 13:17:26 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table un_asset_type
     *
     * @mbg.generated Sun Apr 26 13:17:26 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table un_asset_type
     *
     * @mbg.generated Sun Apr 26 13:17:26 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table un_asset_type
     *
     * @mbg.generated Sun Apr 26 13:17:26 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table un_asset_type
     *
     * @mbg.generated Sun Apr 26 13:17:26 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table un_asset_type
     *
     * @mbg.generated Sun Apr 26 13:17:26 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table un_asset_type
     *
     * @mbg.generated Sun Apr 26 13:17:26 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table un_asset_type
     *
     * @mbg.generated Sun Apr 26 13:17:26 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table un_asset_type
     *
     * @mbg.generated Sun Apr 26 13:17:26 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table un_asset_type
     *
     * @mbg.generated Sun Apr 26 13:17:26 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table un_asset_type
     *
     * @mbg.generated Sun Apr 26 13:17:26 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andDeviceTypeIsNull() {
            addCriterion("device_type is null");
            return (Criteria) this;
        }

        public Criteria andDeviceTypeIsNotNull() {
            addCriterion("device_type is not null");
            return (Criteria) this;
        }

        public Criteria andDeviceTypeEqualTo(String value) {
            addCriterion("device_type =", value, "deviceType");
            return (Criteria) this;
        }

        public Criteria andDeviceTypeNotEqualTo(String value) {
            addCriterion("device_type <>", value, "deviceType");
            return (Criteria) this;
        }

        public Criteria andDeviceTypeGreaterThan(String value) {
            addCriterion("device_type >", value, "deviceType");
            return (Criteria) this;
        }

        public Criteria andDeviceTypeGreaterThanOrEqualTo(String value) {
            addCriterion("device_type >=", value, "deviceType");
            return (Criteria) this;
        }

        public Criteria andDeviceTypeLessThan(String value) {
            addCriterion("device_type <", value, "deviceType");
            return (Criteria) this;
        }

        public Criteria andDeviceTypeLessThanOrEqualTo(String value) {
            addCriterion("device_type <=", value, "deviceType");
            return (Criteria) this;
        }

        public Criteria andDeviceTypeLike(String value) {
            addCriterion("device_type like", value, "deviceType");
            return (Criteria) this;
        }

        public Criteria andDeviceTypeNotLike(String value) {
            addCriterion("device_type not like", value, "deviceType");
            return (Criteria) this;
        }

        public Criteria andDeviceTypeIn(List<String> values) {
            addCriterion("device_type in", values, "deviceType");
            return (Criteria) this;
        }

        public Criteria andDeviceTypeNotIn(List<String> values) {
            addCriterion("device_type not in", values, "deviceType");
            return (Criteria) this;
        }

        public Criteria andDeviceTypeBetween(String value1, String value2) {
            addCriterion("device_type between", value1, value2, "deviceType");
            return (Criteria) this;
        }

        public Criteria andDeviceTypeNotBetween(String value1, String value2) {
            addCriterion("device_type not between", value1, value2, "deviceType");
            return (Criteria) this;
        }

        public Criteria andUnAssetTypeIndexIsNull() {
            addCriterion("un_asset_type_index is null");
            return (Criteria) this;
        }

        public Criteria andUnAssetTypeIndexIsNotNull() {
            addCriterion("un_asset_type_index is not null");
            return (Criteria) this;
        }

        public Criteria andUnAssetTypeIndexEqualTo(String value) {
            addCriterion("un_asset_type_index =", value, "unAssetTypeIndex");
            return (Criteria) this;
        }

        public Criteria andUnAssetTypeIndexNotEqualTo(String value) {
            addCriterion("un_asset_type_index <>", value, "unAssetTypeIndex");
            return (Criteria) this;
        }

        public Criteria andUnAssetTypeIndexGreaterThan(String value) {
            addCriterion("un_asset_type_index >", value, "unAssetTypeIndex");
            return (Criteria) this;
        }

        public Criteria andUnAssetTypeIndexGreaterThanOrEqualTo(String value) {
            addCriterion("un_asset_type_index >=", value, "unAssetTypeIndex");
            return (Criteria) this;
        }

        public Criteria andUnAssetTypeIndexLessThan(String value) {
            addCriterion("un_asset_type_index <", value, "unAssetTypeIndex");
            return (Criteria) this;
        }

        public Criteria andUnAssetTypeIndexLessThanOrEqualTo(String value) {
            addCriterion("un_asset_type_index <=", value, "unAssetTypeIndex");
            return (Criteria) this;
        }

        public Criteria andUnAssetTypeIndexLike(String value) {
            addCriterion("un_asset_type_index like", value, "unAssetTypeIndex");
            return (Criteria) this;
        }

        public Criteria andUnAssetTypeIndexNotLike(String value) {
            addCriterion("un_asset_type_index not like", value, "unAssetTypeIndex");
            return (Criteria) this;
        }

        public Criteria andUnAssetTypeIndexIn(List<String> values) {
            addCriterion("un_asset_type_index in", values, "unAssetTypeIndex");
            return (Criteria) this;
        }

        public Criteria andUnAssetTypeIndexNotIn(List<String> values) {
            addCriterion("un_asset_type_index not in", values, "unAssetTypeIndex");
            return (Criteria) this;
        }

        public Criteria andUnAssetTypeIndexBetween(String value1, String value2) {
            addCriterion("un_asset_type_index between", value1, value2, "unAssetTypeIndex");
            return (Criteria) this;
        }

        public Criteria andUnAssetTypeIndexNotBetween(String value1, String value2) {
            addCriterion("un_asset_type_index not between", value1, value2, "unAssetTypeIndex");
            return (Criteria) this;
        }

        public Criteria andUnAssetTypeNameIsNull() {
            addCriterion("un_asset_type_name is null");
            return (Criteria) this;
        }

        public Criteria andUnAssetTypeNameIsNotNull() {
            addCriterion("un_asset_type_name is not null");
            return (Criteria) this;
        }

        public Criteria andUnAssetTypeNameEqualTo(String value) {
            addCriterion("un_asset_type_name =", value, "unAssetTypeName");
            return (Criteria) this;
        }

        public Criteria andUnAssetTypeNameNotEqualTo(String value) {
            addCriterion("un_asset_type_name <>", value, "unAssetTypeName");
            return (Criteria) this;
        }

        public Criteria andUnAssetTypeNameGreaterThan(String value) {
            addCriterion("un_asset_type_name >", value, "unAssetTypeName");
            return (Criteria) this;
        }

        public Criteria andUnAssetTypeNameGreaterThanOrEqualTo(String value) {
            addCriterion("un_asset_type_name >=", value, "unAssetTypeName");
            return (Criteria) this;
        }

        public Criteria andUnAssetTypeNameLessThan(String value) {
            addCriterion("un_asset_type_name <", value, "unAssetTypeName");
            return (Criteria) this;
        }

        public Criteria andUnAssetTypeNameLessThanOrEqualTo(String value) {
            addCriterion("un_asset_type_name <=", value, "unAssetTypeName");
            return (Criteria) this;
        }

        public Criteria andUnAssetTypeNameLike(String value) {
            addCriterion("un_asset_type_name like", value, "unAssetTypeName");
            return (Criteria) this;
        }

        public Criteria andUnAssetTypeNameNotLike(String value) {
            addCriterion("un_asset_type_name not like", value, "unAssetTypeName");
            return (Criteria) this;
        }

        public Criteria andUnAssetTypeNameIn(List<String> values) {
            addCriterion("un_asset_type_name in", values, "unAssetTypeName");
            return (Criteria) this;
        }

        public Criteria andUnAssetTypeNameNotIn(List<String> values) {
            addCriterion("un_asset_type_name not in", values, "unAssetTypeName");
            return (Criteria) this;
        }

        public Criteria andUnAssetTypeNameBetween(String value1, String value2) {
            addCriterion("un_asset_type_name between", value1, value2, "unAssetTypeName");
            return (Criteria) this;
        }

        public Criteria andUnAssetTypeNameNotBetween(String value1, String value2) {
            addCriterion("un_asset_type_name not between", value1, value2, "unAssetTypeName");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table un_asset_type
     *
     * @mbg.generated do_not_delete_during_merge Sun Apr 26 13:17:26 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table un_asset_type
     *
     * @mbg.generated Sun Apr 26 13:17:26 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}