package com.cloud.platform.model;

public class UnAssetType {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column un_asset_type.id
     *
     * @mbg.generated Sun Apr 26 13:17:26 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column un_asset_type.device_type
     *
     * @mbg.generated Sun Apr 26 13:17:26 CST 2020
     */
    private String deviceType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column un_asset_type.un_asset_type_index
     *
     * @mbg.generated Sun Apr 26 13:17:26 CST 2020
     */
    private String unAssetTypeIndex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column un_asset_type.un_asset_type_name
     *
     * @mbg.generated Sun Apr 26 13:17:26 CST 2020
     */
    private String unAssetTypeName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column un_asset_type.id
     *
     * @return the value of un_asset_type.id
     *
     * @mbg.generated Sun Apr 26 13:17:26 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column un_asset_type.id
     *
     * @param id the value for un_asset_type.id
     *
     * @mbg.generated Sun Apr 26 13:17:26 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column un_asset_type.device_type
     *
     * @return the value of un_asset_type.device_type
     *
     * @mbg.generated Sun Apr 26 13:17:26 CST 2020
     */
    public String getDeviceType() {
        return deviceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column un_asset_type.device_type
     *
     * @param deviceType the value for un_asset_type.device_type
     *
     * @mbg.generated Sun Apr 26 13:17:26 CST 2020
     */
    public void setDeviceType(String deviceType) {
        this.deviceType = deviceType == null ? null : deviceType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column un_asset_type.un_asset_type_index
     *
     * @return the value of un_asset_type.un_asset_type_index
     *
     * @mbg.generated Sun Apr 26 13:17:26 CST 2020
     */
    public String getUnAssetTypeIndex() {
        return unAssetTypeIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column un_asset_type.un_asset_type_index
     *
     * @param unAssetTypeIndex the value for un_asset_type.un_asset_type_index
     *
     * @mbg.generated Sun Apr 26 13:17:26 CST 2020
     */
    public void setUnAssetTypeIndex(String unAssetTypeIndex) {
        this.unAssetTypeIndex = unAssetTypeIndex == null ? null : unAssetTypeIndex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column un_asset_type.un_asset_type_name
     *
     * @return the value of un_asset_type.un_asset_type_name
     *
     * @mbg.generated Sun Apr 26 13:17:26 CST 2020
     */
    public String getUnAssetTypeName() {
        return unAssetTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column un_asset_type.un_asset_type_name
     *
     * @param unAssetTypeName the value for un_asset_type.un_asset_type_name
     *
     * @mbg.generated Sun Apr 26 13:17:26 CST 2020
     */
    public void setUnAssetTypeName(String unAssetTypeName) {
        this.unAssetTypeName = unAssetTypeName == null ? null : unAssetTypeName.trim();
    }
}